#!/usr/bin/env node
//
// wallgrab — bulk wallpaper downloader. Single-file build.
//
// Generated by scripts/build-standalone.mjs from src/. Do not edit by hand;
// change the sources and rebuild. Zero dependencies, Node 18+.
//
import { mkdir, writeFile, stat } from 'node:fs/promises';
import { join } from 'node:path';
import process from 'node:process';

// ──────────────────────────────────────────────────────────────────
// src/ansi.mjs
// ──────────────────────────────────────────────────────────────────
// Terminal primitives: colour, cursor, gradients. No dependencies.

const esc = (s) => `\x1b[${s}`;

const c = {
  reset: esc('0m'),
  bold: esc('1m'),
  dim: esc('2m'),
  italic: esc('3m'),
  underline: esc('4m'),
  inverse: esc('7m'),

  black: esc('30m'),
  red: esc('31m'),
  green: esc('32m'),
  yellow: esc('33m'),
  blue: esc('34m'),
  magenta: esc('35m'),
  cyan: esc('36m'),
  white: esc('37m'),
  gray: esc('90m'),

  bgBlack: esc('40m'),
  bgRed: esc('41m'),
  bgGreen: esc('42m'),
  bgYellow: esc('43m'),
  bgBlue: esc('44m'),
  bgMagenta: esc('45m'),
  bgCyan: esc('46m'),
};

const clearLine = esc('2K');
const cursorUp = (n = 1) => esc(`${n}A`);
const cursorDown = (n = 1) => esc(`${n}B`);
const cursorTo = (col) => esc(`${col + 1}G`);
const hideCursor = esc('?25l');
const showCursor = esc('?25h');
const clearScreen = esc('2J') + esc('H');
const saveCursor = esc('s');
const restoreCursor = esc('u');

/** True when the terminal is very unlikely to render ANSI properly. */
const supportsColor = () => {
  if (process.env.NO_COLOR) return false;
  if (process.env.FORCE_COLOR) return true;
  if (process.platform === 'win32') return true; // Windows Terminal / conhost on Win10+
  const term = process.env.TERM || '';
  if (term === 'dumb') return false;
  return Boolean(process.stdout.isTTY);
};

/** True when we can use 24-bit colour (used for the gradient banner). */
const supportsTrueColor = () => {
  if (!supportsColor()) return false;
  const term = process.env.TERM || '';
  const ci = process.env.CI ? true : false;
  return /truecolor|24bit/i.test(process.env.COLORTERM || '') ||
    /xterm-256|alacritty|kitty|wezterm|ghostty|iterm|tmux/i.test(term) ||
    ci || process.platform === 'win32';
};

// Theme accents, resolved once at load.
const CYAN = supportsTrueColor() ? esc('38;2;0;198;255m') : c.cyan;
const AMBER = supportsTrueColor() ? esc('38;2;255;195;113m') : c.yellow;
const GREEN = supportsTrueColor() ? esc('38;2;56;239;125m') : c.green;

const hexToRgb = (hex) => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
];

const rgbFg = ([r, g, b]) => esc(`38;2;${r};${g};${b}m`);
const rgbBg = ([r, g, b]) => esc(`48;2;${r};${g};${b}m`);

const lerp = (a, b, t) => Math.round(a + (b - a) * t);
const mix = (from, to, t) => [
  lerp(from[0], to[0], t),
  lerp(from[1], to[1], t),
  lerp(from[2], to[2], t),
];

/**
 * Paint every visible column of `text` with a horizontal gradient.
 * Multiline strings keep the same gradient phase on every line so the
 * banner reads as one continuous sweep.
 */
function gradient(text, stops) {
  if (!supportsTrueColor()) return text;
  const rgbStops = stops.map(hexToRgb);
  const lines = text.split('\n');
  const width = Math.max(...lines.map((l) => [...l].length));

  return lines
    .map((line) => {
      let col = 0;
      let out = '';
      for (const ch of line) {
        if (ch === ' ') {
          out += ' ';
          col++;
          continue;
        }
        const t = width <= 1 ? 0 : col / (width - 1);
        out += rgbFg(sample(rgbStops, t)) + ch + c.reset;
        col++;
      }
      return out;
    })
    .join('\n');
}

function sample(stops, t) {
  if (stops.length === 1) return stops[0];
  const scaled = t * (stops.length - 1);
  const i = Math.min(Math.floor(scaled), stops.length - 2);
  return mix(stops[i], stops[i + 1], scaled - i);
}

/** Vertical variant — used for the sidebar rules and the progress bar. */
function gradientRows(rows, stops) {
  return rows.map((r, i) => {
    const t = rows.length <= 1 ? 0 : i / (rows.length - 1);
    if (!supportsTrueColor()) return r;
    return rgbFg(sample(stops.map(hexToRgb), t)) + r + c.reset;
  });
}

/** Strip ANSI so we can measure real display width. */
// eslint-disable-next-line no-control-regex
const strip = (s) => s.replace(/\x1b\[[0-9;?]*[a-zA-Z]/g, '');
const width = (s) => [...strip(s)].length;

/** Bar like ▓▓▓▓░░░░ for a 0..1 fraction. */
function bar(fraction, size = 24) {
  const f = Math.max(0, Math.min(1, fraction));
  const filled = Math.round(f * size);
  return '█'.repeat(filled) + '░'.repeat(size - filled);
}

const pad = (s, n, align = 'left') => {
  const w = width(s);
  if (w >= n) return s;
  const gap = ' '.repeat(n - w);
  if (align === 'right') return gap + s;
  if (align === 'center') {
    const l = Math.floor((n - w) / 2);
    return ' '.repeat(l) + s + ' '.repeat(n - w - l);
  }
  return s + gap;
};


// import aliases re-bound by the bundler
const sw = width;


// ──────────────────────────────────────────────────────────────────
// src/sources.mjs
// ──────────────────────────────────────────────────────────────────
// Twelve wallpaper sources behind one interface.
//
// Each source returns [{ url, name, ext, width, height, credit }].
// `keyEnv` marks sources that need a free API key; the CLI asks for it and
// explains where to get one, rather than failing with a 401.

const JSON_HEADERS = { Accept: 'application/json', 'User-Agent': UA() };

function UA() {
  return 'wallgrab/1.0 (+https://github.com/bhavyam2468/get-wallpapers)';
}

async function getJSON(url, headers = {}) {
  const res = await fetch(url, { headers: { ...JSON_HEADERS, ...headers }, redirect: 'follow' });
  if (!res.ok) {
    const body = (await res.text().catch(() => '')).slice(0, 180).replace(/\s+/g, ' ');
    throw new Error(`HTTP ${res.status} ${res.statusText}${body ? ` — ${body}` : ''}`);
  }
  const text = await res.text();
  if (text.trimStart().startsWith('<')) {
    throw new Error('server answered with HTML instead of JSON (rate limited or blocked?)');
  }
  return JSON.parse(text);
}

const extFrom = (url, fallback = 'jpg') => {
  try {
    const p = new URL(url).pathname;
    const m = p.match(/\.(jpe?g|png|webp|gif|avif|bmp)$/i);
    return m ? m[1].toLowerCase().replace('jpeg', 'jpg') : fallback;
  } catch {
    return fallback;
  }
};

const safeFile = (s, max = 70) =>
  (s || 'wallpaper')
    .replace(/[^\w.\- ]+/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, max) || 'wallpaper';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Fetch pages until we have `count` items. Handles per-API page caps. */
async function paginate(pageSize, count, fetchPage, delay = 220) {
  const out = [];
  for (let page = 1; out.length < count; page++) {
    const items = await fetchPage(page, pageSize);
    if (!items || items.length === 0) break;
    out.push(...items);
    if (items.length < pageSize) break; // last page
    if (out.length < count) await sleep(delay);
  }
  return out.slice(0, count);
}

// ─────────────────────────────────────────────────────────────── wallhaven

const wallhaven = {
  id: 'wallhaven',
  name: 'Wallhaven',
  blurb: 'the community giant — 19k+ minimal, 12k+ abstract, full-res originals',
  keyEnv: null,
  defaults: { query: 'minimal', count: 100 },
  extra: [
    {
      key: 'resolution',
      label: 'at',
      value: '2560x1440',
      options: ['any', '1920x1080', '2560x1440', '3440x1440', '3840x2160', '5120x2880', '7680x4320'],
      hint: 'minimum resolution',
    },
    {
      key: 'sort',
      label: 'sorted by',
      value: 'favorites',
      options: ['favorites', 'toplist', 'date_added', 'views', 'random', 'relevance'],
    },
    {
      key: 'ratio',
      label: 'shaped',
      value: '16x9',
      options: ['any', '16x9', '16x10', '21x9', '32x9', '9x16', '4x3', '1x1'],
    },
    {
      key: 'color',
      label: 'tinted',
      value: 'any',
      options: ['any', '660000', '990000', 'cc0000', 'cc3333', 'ea4c88', '993399',
        '663399', '333399', '0066cc', '0099cc', '66cccc', '77cc33', '669900',
        '336600', '666600', '999900', 'cccc33', 'ffff00', 'ffcc33', 'ff9900',
        'ff6600', 'cc6633', '996633', '663300', '000000', '999999', 'cccccc',
        '424153', 'ffffff'],
      hint: 'dominant colour hex',
    },
    {
      key: 'category',
      label: 'kind',
      value: 'general',
      options: ['general', 'anime', 'people', 'general+anime', 'all'],
    },
  ],
  async search({ query, count, resolution, sort, ratio, color, category }) {
    const catMap = {
      general: '100', anime: '010', people: '001',
      'general+anime': '110', all: '111',
    };
    return paginate(24, count, async (page) => {
      const p = new URLSearchParams({
        q: query, page: String(page), purity: '100',
        categories: catMap[category] || '111',
        sorting: sort || 'favorites', order: 'desc',
      });
      if (resolution && resolution !== 'any') p.set('atleast', resolution);
      if (ratio && ratio !== 'any') p.set('ratios', ratio);
      if (color && color !== 'any') p.set('colors', color.replace('#', ''));

      const data = await getJSON(`https://wallhaven.cc/api/v1/search?${p}`);
      return (data.data || []).map((w) => {
        const [width, height] = (w.resolution || '0x0').split('x').map(Number);
        return {
          url: w.path,
          name: `wallhaven_${w.id}_${w.resolution}`,
          ext: extFrom(w.path),
          width, height,
          credit: `wallhaven · ${w.id}`,
        };
      });
    });
  },
};

// ─────────────────────────────────────────────────────────────────── nasa

const nasa = {
  id: 'nasa',
  name: 'NASA',
  blurb: 'public-domain deep space, ultra-high resolution, no key needed',
  keyEnv: null,
  defaults: { query: 'nebula', count: 60 },
  extra: [],
  async search({ query, count }) {
    return paginate(100, count, async (page) => {
      const p = new URLSearchParams({
        q: query, media_type: 'image', page: String(page), per_page: '100',
      });
      const data = await getJSON(`https://images-api.nasa.gov/search?${p}`);
      return (data.collection?.items || [])
        .map((it) => {
          const link = it.links?.[0]?.href;
          if (!link) return null;
          // prefer the original, then large, then whatever we got
          const orig = link.replace(/~(large|medium|small|thumb)\./, '~orig.');
          return {
            url: orig,
            name: `nasa_${safeFile(it.data?.[0]?.nasa_id || it.data?.[0]?.title, 60)}`,
            ext: extFrom(link),
            width: 0, height: 0,
            credit: `NASA · ${it.data?.[0]?.photographer || 'public domain'}`,
          };
        })
        .filter(Boolean);
    });
  },
};

// ───────────────────────────────────────────────────────────────── openverse

const openverse = {
  id: 'openverse',
  name: 'Openverse',
  blurb: '600M+ openly-licensed images, filtered by license for you',
  keyEnv: null,
  defaults: { query: 'abstract', count: 60 },
  extra: [
    {
      key: 'license',
      label: 'licensed',
      value: 'any',
      options: ['any', 'all-cc', 'cc0', 'by', 'by-sa', 'public-domain-mark'],
    },
    {
      key: 'size',
      label: 'sized',
      value: 'any',
      options: ['any', 'small', 'medium', 'large'],
    },
  ],
  async search({ query, count, license, size }) {
    return paginate(50, count, async (page) => {
      const p = new URLSearchParams({ q: query, page: String(page), page_size: '50' });
      const licMap = {
        'all-cc': 'cc0,by,by-sa,by-nd,by-nc,by-nc-sa,by-nc-nd',
        'public-domain-mark': 'public-domain-mark',
      };
      if (license && license !== 'any') p.set('license', licMap[license] || license);
      if (size && size !== 'any') p.set('size', size);

      const data = await getJSON(`https://api.openverse.org/v1/images/?${p}`);
      return (data.results || []).map((r) => ({
        url: r.url,
        name: `openverse_${safeFile(r.title || r.id, 60)}`,
        ext: extFrom(r.url),
        width: r.width || 0, height: r.height || 0,
        credit: `${r.license?.toUpperCase()} · ${r.creator || 'unknown'}`,
      }));
    });
  },
};

// ───────────────────────────────────────────────────────────────────── met

const met = {
  id: 'met',
  name: 'The Met',
  blurb: 'Metropolitan Museum highlights — paintings as maximalist wallpapers',
  keyEnv: null,
  defaults: { query: 'abstract', count: 40 },
  extra: [],
  async search({ query, count }) {
    const q = new URLSearchParams({ q: query, isHighlight: 'true', hasImages: 'true' });
    const found = await getJSON(`https://collectionapi.metmuseum.org/public/collection/v1/search?${q}`);
    const ids = (found.objectIDs || []).slice(0, Math.min(count * 2, 250));
    if (!ids.length) return [];

    const out = [];
    for (const id of ids) {
      if (out.length >= count) break;
      try {
        const o = await getJSON(
          `https://collectionapi.metmuseum.org/public/collection/v1/objects/${id}`,
        );
        if (!o.primaryImage) continue;
        out.push({
          url: o.primaryImage,
          name: `met_${safeFile(o.title || String(id), 60)}`,
          ext: extFrom(o.primaryImage),
          width: 0, height: 0,
          credit: `The Met · ${o.artistDisplayName || 'unknown'} · public domain`,
        });
      } catch { /* skip a single bad record */ }
      await sleep(60);
    }
    return out;
  },
};

// ─────────────────────────────────────────────────────────────────── artic

const artic = {
  id: 'artic',
  name: 'Art Institute of Chicago',
  blurb: '132k+ works served over IIIF, any resolution you ask for',
  keyEnv: null,
  defaults: { query: 'abstract', count: 40 },
  extra: [
    {
      key: 'iiifWidth',
      label: 'rendered at',
      value: '2000px',
      options: ['843px', '1686px', '2000px', '3000px', 'full'],
      hint: 'IIIF render width',
    },
  ],
  async search({ query, count, iiifWidth }) {
    const w = (iiifWidth || '2000px').replace('px', '');
    return paginate(50, count, async (page) => {
      const p = new URLSearchParams({
        q: query, limit: '50', page: String(page),
        fields: 'id,title,image_id,artist_display,date_display',
      });
      const data = await getJSON(`https://api.artic.edu/api/v1/artworks/search?${p}`);
      return (data.data || [])
        .filter((a) => a.image_id)
        .map((a) => ({
          url: `https://www.artic.edu/iiif/2/${a.image_id}/full/,${w},/0/default.jpg`,
          name: `artic_${safeFile(a.title || String(a.id), 60)}`,
          ext: 'jpg',
          width: 0, height: 0,
          credit: `Art Institute of Chicago · ${a.artist_display || 'unknown'}`,
        }));
    });
  },
};

// ────────────────────────────────────────────────────────────────── picsum

const picsum = {
  id: 'picsum',
  name: 'Lorem Picsum',
  blurb: 'infinite random photography, rendered to any size you want',
  keyEnv: null,
  defaults: { query: 'any', count: 50 },
  extra: [
    {
      key: 'size',
      label: 'at',
      value: '3840x2160',
      options: ['1920x1080', '2560x1440', '3840x2160', '5120x2880', '1080x1920', '1440x2560'],
      hint: 'rendered size',
    },
    {
      key: 'mode',
      label: 'style',
      value: 'color',
      options: ['color', 'grayscale', 'blurred'],
    },
  ],
  async search({ count, size, mode }) {
    const [w, h] = (size || '3840x2160').split('x');
    const pool = [];
    for (let page = 1; pool.length < count * 2 && page <= 6; page++) {
      const list = await getJSON(`https://picsum.photos/v2/list?page=${page}&limit=100`);
      if (!Array.isArray(list) || !list.length) break;
      pool.push(...list);
      await sleep(150);
    }
    return pool.slice(0, count).map((img) => {
      let u = `https://picsum.photos/id/${img.id}/${w}/${h}`;
      if (mode === 'grayscale') u += '?grayscale';
      if (mode === 'blurred') u += '?blur=2';
      return {
        url: u,
        name: `picsum_${img.id}_${w}x${h}${mode === 'grayscale' ? '_gray' : ''}`,
        ext: 'jpg',
        width: +w, height: +h,
        credit: `Lorem Picsum · ${img.author}`,
      };
    });
  },
};

// ────────────────────────────────────────────────────────────────── github

const github = {
  id: 'github',
  name: 'GitHub collection',
  blurb: 'curated wallpaper repos — hundreds of images, no git clone needed',
  keyEnv: null,
  defaults: { query: 'AngelJumbo/gruvbox-wallpapers', count: 150 },
  extra: [
    {
      key: 'repo',
      label: 'repo',
      value: 'AngelJumbo/gruvbox-wallpapers',
      options: [
        'AngelJumbo/gruvbox-wallpapers', 'D3Ext/aesthetic-wallpapers',
        'linuxdotexe/nordic-wallpapers', 'dharmx/walls', 'rose-pine/wallpapers',
        'makccr/wallpapers', 'vyrx-dev/Wallpapers', 'elementary/wallpapers',
        'Narmis-E/onedark-wallpapers', 'vinceliuice/WhiteSur-wallpapers',
      ],
      hint: 'owner/name — type your own',
      freeform: true,
    },
    {
      key: 'filter',
      label: 'matching',
      value: 'any',
      options: ['any', 'abstract', 'minimal', 'dark', '4k', 'nature', 'gradient'],
      hint: 'substring of the file path',
    },
    {
      key: 'pick',
      label: 'picking',
      value: 'largest',
      options: ['largest', 'first', 'random'],
    },
  ],
  async search({ count, repo, filter, pick }) {
    const r = (repo || '').trim().replace(/^https?:\/\/github\.com\//, '').replace(/\.git$/, '');
    if (!/^[\w.-]+\/[\w.-]+$/.test(r)) {
      throw new Error(`repo "${r}" should look like owner/name, e.g. dharmx/walls`);
    }
    const meta = await getJSON(`https://api.github.com/repos/${r}`);
    const branch = meta.default_branch || 'main';
    const tree = await getJSON(
      `https://api.github.com/repos/${r}/git/trees/${branch}?recursive=1`,
    );

    const IMG = /\.(jpe?g|png|webp|gif|avif|bmp)$/i;
    let files = (tree.tree || [])
      .filter((e) => e.type === 'blob' && IMG.test(e.path) && (e.size || 0) > 100 * 1024)
      .filter((e) => !filter || filter === 'any' || e.path.toLowerCase().includes(filter.toLowerCase()))
      .map((e) => ({ path: e.path, size: e.size || 0 }));

    if (tree.truncated) {
      throw new Error(
        `GitHub truncated the file list for ${r} — the repo is too big. ` +
        `Try a narrower --filter or a smaller repo.`,
      );
    }
    if (!files.length) throw new Error(`no images matched in ${r}`);

    if (pick === 'largest') files.sort((a, b) => b.size - a.size);
    if (pick === 'random') files.sort(() => Math.random() - 0.5);

    return files.slice(0, count).map((f) => ({
      url: `https://raw.githubusercontent.com/${r}/${branch}/${encodeURI(f.path).replace(/#/g, '%23')}`,
      name: `${safeFile(f.path.split('/').pop().replace(IMG, ''), 60)}`,
      ext: (f.path.match(IMG) || ['.jpg'])[0].slice(1).toLowerCase().replace('jpeg', 'jpg'),
      width: 0, height: 0,
      credit: `github · ${r}`,
    }));
  },
};

// ───────────────────────────────────────────────────────────────── reddit

const reddit = {
  id: 'reddit',
  name: 'Reddit',
  blurb: 'top posts from wallpaper subreddits (can be blocked from datacenter IPs)',
  keyEnv: null,
  defaults: { query: 'wallpaper', count: 100 },
  extra: [
    {
      key: 'subreddit',
      label: 'from r/',
      value: 'wallpaper',
      options: ['wallpaper', 'wallpapers', 'MinimalWallpaper', 'WidescreenWallpaper',
        'Amoledbackgrounds', 'EarthPorn', 'SpacePorn', 'ImaginaryLandscapes',
        'CyberpunkWallpapers', 'Animewallpaper', 'WallpaperRequests'],
      freeform: true,
    },
    {
      key: 'window',
      label: 'top of',
      value: 'year',
      options: ['hour', 'day', 'week', 'month', 'year', 'all'],
    },
  ],
  async search({ count, subreddit, window: win }) {
    const sub = (subreddit || 'wallpaper').replace(/^r\//, '');
    let after = null;
    const out = [];
    while (out.length < count) {
      const p = new URLSearchParams({ t: win || 'year', limit: '100', raw_json: '1' });
      if (after) p.set('after', after);
      const data = await getJSON(`https://www.reddit.com/r/${sub}/top.json?${p}`);
      const kids = data.data?.children || [];
      if (!kids.length) break;
      for (const k of kids) {
        const d = k.data;
        if (d.over_18 || d.stickied) continue;
        let url = d.preview?.images?.[0]?.source?.url?.replace(/&amp;/g, '&');
        if (!url && /\.(jpe?g|png|webp)$/i.test(d.url || '')) url = d.url;
        if (!url || d.is_video || d.post_hint === 'hosted:video') continue;
        out.push({
          url,
          name: `reddit_${safeFile(d.title, 60)}_${d.id}`,
          ext: extFrom(url),
          width: d.preview?.images?.[0]?.source?.width || 0,
          height: d.preview?.images?.[0]?.source?.height || 0,
          credit: `r/${sub} · ${d.score} pts · u/${d.author}`,
        });
        if (out.length >= count) break;
      }
      after = data.data?.after;
      if (!after) break;
      await sleep(600);
    }
    return out.slice(0, count);
  },
};

// ─────────────────────────────────────────────────────────────── keyed ones

const unsplash = {
  id: 'unsplash',
  name: 'Unsplash',
  blurb: 'professional photography — the best minimal & abstract library',
  keyEnv: 'UNSPLASH_ACCESS_KEY',
  keyHint: 'free key → https://unsplash.com/developers (new "Demo" app, 50 req/hr)',
  defaults: { query: 'minimal', count: 90 },
  extra: [
    {
      key: 'orientation',
      label: 'oriented',
      value: 'landscape',
      options: ['landscape', 'portrait', 'squarish', 'any'],
    },
    {
      key: 'sort',
      label: 'sorted by',
      value: 'relevant',
      options: ['relevant', 'latest'],
    },
  ],
  async search({ query, count, orientation, sort }, key) {
    return paginate(30, count, async (page) => {
      const p = new URLSearchParams({ query, page: String(page), per_page: '30' });
      if (orientation && orientation !== 'any') p.set('orientation', orientation);
      if (sort) p.set('order_by', sort);
      const data = await getJSON(`https://api.unsplash.com/search/photos?${p}`, {
        Authorization: `Client-ID ${key}`,
        'Accept-Version': 'v1',
      });
      return (data.results || []).map((r) => ({
        url: `${r.urls.raw}&fm=jpg&q=85`,
        name: `unsplash_${safeFile(r.slug || r.id, 60)}`,
        ext: 'jpg',
        width: r.width || 0, height: r.height || 0,
        credit: `Unsplash · ${r.user?.name || 'unknown'} · unsplash.com/license`,
      }));
    }, 1200); // demo tier is 50 req/hr — go slow
  },
};

const pexels = {
  id: 'pexels',
  name: 'Pexels',
  blurb: 'editorial-quality stock, strong on minimal & architecture',
  keyEnv: 'PEXELS_API_KEY',
  keyHint: 'free key → https://www.pexels.com/api/ (200 req/hr)',
  defaults: { query: 'minimalist', count: 100 },
  extra: [
    {
      key: 'orientation',
      label: 'oriented',
      value: 'landscape',
      options: ['landscape', 'portrait', 'square', 'any'],
    },
    {
      key: 'color',
      label: 'tinted',
      value: 'any',
      options: ['any', 'black_and_white', 'black', 'white', 'yellow', 'orange',
        'red', 'purple', 'magenta', 'green', 'teal', 'blue'],
    },
  ],
  async search({ query, count, orientation, color }, key) {
    return paginate(80, count, async (page) => {
      const p = new URLSearchParams({ query, page: String(page), per_page: '80' });
      if (orientation && orientation !== 'any') p.set('orientation', orientation);
      if (color && color !== 'any') p.set('color', color);
      const data = await getJSON(`https://api.pexels.com/v1/search?${p}`, {
        Authorization: key,
      });
      return (data.photos || []).map((r) => ({
        url: r.src.original,
        name: `pexels_${r.id}_${safeFile(r.alt, 50)}`,
        ext: extFrom(r.src.original),
        width: r.width || 0, height: r.height || 0,
        credit: `Pexels · ${r.photographer}`,
      }));
    }, 300);
  },
};

const pixabay = {
  id: 'pixabay',
  name: 'Pixabay',
  blurb: '4M+ photos, illustrations and vectors — best for graphic abstracts',
  keyEnv: 'PIXABAY_API_KEY',
  keyHint: 'free key → https://pixabay.com/api/docs/',
  defaults: { query: 'abstract', count: 100 },
  extra: [
    {
      key: 'imageType',
      label: 'kind',
      value: 'all',
      options: ['all', 'photo', 'illustration', 'vector'],
    },
    {
      key: 'orientation',
      label: 'oriented',
      value: 'horizontal',
      options: ['horizontal', 'vertical', 'any'],
    },
    {
      key: 'color',
      label: 'tinted',
      value: 'any',
      options: ['any', 'grayscale', 'transparent', 'red', 'orange', 'yellow',
        'green', 'turquoise', 'blue', 'lilac', 'pink', 'white', 'black', 'brown'],
    },
  ],
  async search({ query, count, imageType, orientation, color }, key) {
    return paginate(200, count, async (page) => {
      const p = new URLSearchParams({
        key, q: query, page: String(page), per_page: '200', safesearch: 'true',
      });
      if (imageType && imageType !== 'all') p.set('image_type', imageType);
      if (orientation && orientation !== 'any') p.set('orientation', orientation);
      if (color && color !== 'any') p.set('colors', color);
      const data = await getJSON(`https://pixabay.com/api/?${p}`);
      return (data.hits || []).map((r) => ({
        url: r.largeImageURL,
        name: `pixabay_${r.id}_${safeFile(r.tags?.split(',')[0], 50)}`,
        ext: extFrom(r.largeImageURL),
        width: r.imageWidth || 0, height: r.imageHeight || 0,
        credit: `Pixabay · ${r.user} · pixabay.com/service/license`,
      }));
    }, 300);
  },
};

const SOURCES = [
  wallhaven, unsplash, nasa, openverse, pexels, pixabay,
  artic, met, picsum, github, reddit,
];

const byId = (id) => SOURCES.find((s) => s.id === id);

/** Formats each source can actually produce, used to constrain the format token. */
const FORMATS = ['jpg', 'png', 'webp', 'gif', 'avif', 'any'];


// ──────────────────────────────────────────────────────────────────
// src/download.mjs
// ──────────────────────────────────────────────────────────────────
// Concurrent downloader with resume, magic-byte verification and live progress.


const MAGIC = {
  jpg: (b) => b[0] === 0xff && b[1] === 0xd8,
  png: (b) => b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e,
  gif: (b) => b[0] === 0x47 && b[1] === 0x49 && b[2] === 0x46,
  // WebP is a RIFF container: "RIFF" at 0..3, "WEBP" at 8..11
  webp: (b) => b.length > 11 &&
    b[0] === 0x52 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x46 &&
    b[8] === 0x57 && b[9] === 0x45 && b[10] === 0x42 && b[11] === 0x50,
  bmp: (b) => b[0] === 0x42 && b[1] === 0x4d,
  avif: (b) => b.length > 12 && b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70,
};

/** What format did the server *actually* send us? */
function sniff(buf) {
  for (const [k, test] of Object.entries(MAGIC)) if (test(buf)) return k;
  return null;
}

const uniq = (dir, base, ext) => {
  let name = `${base}.${ext}`;
  let i = 2;
  // cheap dedupe: stat is fast enough at these volumes
  const exists = async (n) => { try { await stat(join(dir, n)); return true; } catch { return false; } };
  return (async () => {
    while (await exists(name)) name = `${base}-${i++}.${ext}`;
    return name;
  })();
};

async function downloadAll(items, opts = {}) {
  const {
    dir = './wallpapers',
    format = 'any',
    concurrency = 6,
    retries = 3,
    onProgress = () => {},
    signal,
  } = opts;

  await mkdir(dir, { recursive: true });

  const state = {
    done: 0, ok: 0, skipped: 0, failed: 0, bytes: 0,
    total: items.length, current: '', startedAt: Date.now(), errors: [],
  };

  const queue = [...items];
  let cursor = 0;

  async function worker() {
    while (cursor < queue.length) {
      if (signal?.aborted) return;
      const item = queue[cursor++];
      state.current = item.name;
      try {
        const buf = await fetchWithRetry(item.url, retries);
        const actual = sniff(buf) || extOf(item.ext);

        // Honour the format token: keep only what really is that format.
        if (format !== 'any' && actual !== format) {
          state.skipped++;
          state.errors.push({ name: item.name, why: `is ${actual}, not ${format}` });
          continue;
        }

        const name = await uniq(dir, item.name, actual);
        await writeFile(join(dir, name), buf);
        state.ok++;
        state.bytes += buf.length;
      } catch (e) {
        state.failed++;
        state.errors.push({ name: item.name, why: e.message });
      } finally {
        state.done++;
        onProgress(state);
      }
    }
  }

  const workers = Array.from({ length: Math.max(1, concurrency) }, worker);
  await Promise.all(workers);
  state.elapsed = (Date.now() - state.startedAt) / 1000;
  return state;
}

const extOf = (e) => (e || 'jpg').toLowerCase().replace('jpeg', 'jpg');

async function fetchWithRetry(url, retries) {
  let last;
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url, {
        redirect: 'follow',
        headers: { 'User-Agent': 'wallgrab/1.0 (+https://github.com/bhavyam2468/get-wallpapers)' },
        signal: AbortSignal.timeout(60_000),
      });
      if (res.status === 429 || res.status >= 500) {
        throw new Error(`HTTP ${res.status}`);
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const buf = Buffer.from(await res.arrayBuffer());
      if (!buf.length) throw new Error('empty response');
      return buf;
    } catch (e) {
      last = e;
      await new Promise((r) => setTimeout(r, 400 * 2 ** i));
    }
  }
  throw last;
}

/** Bytes → human, and seconds → m:ss. */
const humanBytes = (n) => {
  if (n < 1024) return `${n} B`;
  const u = ['KB', 'MB', 'GB', 'TB'];
  let v = n / 1024, i = 0;
  while (v >= 1024 && i < u.length - 1) { v /= 1024; i++; }
  return `${v.toFixed(v < 10 ? 1 : 0)} ${u[i]}`;
};

const humanTime = (s) => {
  if (!isFinite(s) || s < 0) return '--:--';
  const m = Math.floor(s / 60);
  const sec = Math.floor(s % 60);
  return `${m}:${String(sec).padStart(2, '0')}`;
};


// ──────────────────────────────────────────────────────────────────
// src/banner.mjs
// ──────────────────────────────────────────────────────────────────
// ANSI-shadow glyphs, 8 columns wide, 6 rows tall.
const GLYPHS = {
  W: ['██╗    ██╗', '██║    ██║', '██║ █╗ ██║', '██║███╗██║', '╚███╔███╔╝', ' ╚══╝╚══╝ '],
  A: [' █████╗ ', '██╔══██╗', '███████║', '██╔══██║', '██║  ██║', '╚═╝  ╚═╝'],
  L: ['██╗     ', '██║     ', '██║     ', '██║     ', '███████╗', '╚══════╝'],
  G: [' ██████╗ ', '██╔════╝ ', '██║  ███╗', '██║   ██║', '╚██████╔╝', ' ╚═════╝ '],
  R: ['██████╗ ', '██╔══██╗', '██████╔╝', '██╔══██╗', '██║  ██║', '╚═╝  ╚═╝'],
  B: ['██████╗ ', '██╔══██╗', '██████╔╝', '██╔══██╗', '██████╔╝', '╚═════╝ '],
  ' ': ['        ', '        ', '        ', '        ', '        ', '        '],
};

const word = (w) => {
  const rows = ['', '', '', '', '', ''];
  for (const ch of w.toUpperCase()) {
    const g = GLYPHS[ch] || GLYPHS[' '];
    g.forEach((line, i) => { rows[i] += line; });
  }
  return rows;
};

const THEME = {
  sunset: ['#ff5f6d', '#ffc371'],
  ocean: ['#00c6ff', '#0072ff'],
  grape: ['#8e2de2', '#4a00e0'],
  mint: ['#11998e', '#38ef7d'],
  ember: ['#f7971e', '#ffd200'],
  rose: ['#ee9ca7', '#ff6a88'],
};

/**
 * Big gradient banner. Falls back to plain text on terminals without
 * truecolour so it never prints garbage.
 */
function banner(theme = 'sunset') {
  const rows = word('WALLGRAB');
  const stops = THEME[theme] || THEME.sunset;
  const art = supportsTrueColor() ? gradient(rows.join('\n'), stops) : rows.join('\n');

  const tagline = gradientRows([
    '  bulk wallpapers · eleven sources · zero dependencies',
    '  ↑↓ pick a value · ←→ move between them · ⏎ grab',
  ], stops);

  return `\n${art}\n\n${tagline.join('\n')}\n`;
}

/** Horizontal rule that matches the theme. */
function rule(char = '─', n = 74, theme = 'sunset') {
  const stops = THEME[theme] || THEME.sunset;
  const line = char.repeat(n);
  return supportsTrueColor() ? gradient(line, stops) : line;
}

/** Small framed box used for the completion summary. */
function box(lines, title, theme = 'sunset') {
  const inner = Math.max(
    ...lines.map((l) => [...strip(l)].length),
    title ? [...title].length + 4 : 0,
  );
  const w = Math.min(inner + 2, 72);
  const stops = THEME[theme] || THEME.sunset;
  const paint = (s) => (supportsTrueColor() ? gradient(s, stops) : s);

  const top = title
    ? `╭─${c.bold} ${title} ${c.reset}${paint('─'.repeat(Math.max(0, w - title.length - 4)))}╮`
    : paint(`╭${'─'.repeat(w)}╮`);
  const bottom = paint(`╰${'─'.repeat(w)}╯`);
  const body = lines.map(
    (l) => `${paint('│')} ${pad(strip(l), w - 2)} ${paint('│')}`,
  );
  return [top, ...body, bottom].join('\n');
}


const SPINNER = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];


// ──────────────────────────────────────────────────────────────────
// src/tokens.mjs
// ──────────────────────────────────────────────────────────────────
// The inline editable command sentence.
//
//   download ⟨100⟩ ⟨minimal⟩ wallpapers from ⟨wallhaven⟩ as ⟨jpg⟩ into ⟨./wallpapers⟩
//
// ←/→ move between the ⟨tokens⟩, ↑/↓ cycle their values, typing filters the
// option list and lets you enter a custom value, ⏎ commits.


/** Build the token list for a source, keeping values the user already set. */
function buildTokens(sourceId, prev = {}) {
  const src = byId(sourceId);
  const tokens = [
    {
      key: 'count', label: 'download', value: prev.count ?? String(src?.defaults.count ?? 100),
      options: ['10', '25', '50', '100', '250', '500', '1000'],
      suffix: '', validate: (v) => (/^\d+$/.test(v) && +v > 0) ? null : 'needs a whole number',
    },
    {
      key: 'query', label: '', value: prev.query ?? src?.defaults.query ?? 'minimal',
      options: ['minimal', 'minimalism', 'abstract', 'geometric', 'gradient', 'dark',
        'nature', 'space', 'city', 'architecture', 'texture', 'vaporwave', 'topographic'],
      freeform: true, hint: 'search terms',
    },
    {
      key: 'source', label: 'wallpapers from',
      value: sourceId,
      options: null, // filled below from the registry
      sourceToken: true,
    },
    {
      key: 'format', label: 'as', value: prev.format ?? 'any',
      options: FORMATS, hint: 'kept files must really be this format',
    },
    {
      key: 'dir', label: 'into', value: prev.dir ?? './wallpapers',
      freeform: true, hint: 'output folder',
    },
  ];

  for (const extra of src?.extra || []) {
    tokens.push({
      ...extra,
      value: prev[extra.key] ?? extra.value,
      label: extra.label,
    });
  }
  return tokens;
}

/**
 * Stateful editor. `render()` returns the exact lines to draw; the caller owns
 * the screen and just replays them.
 */
class SentenceEditor {
  constructor(sourceId, initial = {}) {
    this.tokens = buildTokens(sourceId, initial);
    this.index = 0;
    this.typing = null; // null, or the partial string being typed
    this.menuOffset = 0;
    this.lastLines = 0;
    this.error = null;
  }

  get token() { return this.tokens[this.index]; }
  get values() { return Object.fromEntries(this.tokens.map((t) => [t.key, t.value])); }

  /** Options for the selected token, honouring the active type-filter. */
  options() {
    const t = this.token;
    if (t.sourceToken) {
      return SOURCES.map((s) => s.id);
    }
    let opts = t.options ? [...t.options] : [];
    if (this.typing) {
      const q = this.typing.toLowerCase();
      const hits = opts.filter((o) => o.toLowerCase().includes(q));
      opts = hits;
      if (t.freeform !== false && !opts.some((o) => o === this.typing)) {
        opts = [this.typing, ...opts];
      }
    }
    return opts;
  }

  move(delta) {
    const n = this.tokens.length;
    this.index = (this.index + delta + n) % n;
    this.typing = null; this.menuOffset = 0; this.error = null;
    // switching source rebuilds the extra tokens
    if (this.token.sourceToken) this._noteSource = true;
  }

  cycle(delta) {
    const opts = this.options();
    if (!opts.length) return;
    const cur = opts.indexOf(this.typing ?? this.token.value);
    const next = cur === -1
      ? (delta > 0 ? 0 : opts.length - 1)
      : (cur + delta + opts.length) % opts.length;
    this.menuOffset = Math.max(0, next - 5);
    this._apply(opts[next]);
  }

  jumpTo(value) {
    this.menuOffset = 0;
    this._apply(value);
  }

  _apply(value) {
    const t = this.token;
    if (t.validate) {
      const err = t.validate(value);
      if (err) { this.error = err; return; }
    }
    t.value = value;
    this.error = null;
    if (t.sourceToken) {
      const keep = this.values;
      this.tokens = buildTokens(value, keep);
      this.index = this.tokens.findIndex((x) => x.key === 'source');
    }
  }

  typeChar(ch) {
    // First keystroke starts from an empty buffer, not from the old value.
    this.typing = (this.typing ?? '') + ch;
    this.menuOffset = 0;
    this._apply(this.typing);
  }

  clearTyping() {
    this.typing = '';
    this.menuOffset = 0;
    if (this.token.freeform) this._apply('');
  }

  cancelTyping() { this.typing = null; this.error = null; this.menuOffset = 0; }

  /**
   * Validate everything on ⏎. Returns an error string, or null if the
   * sentence is safe to run. Keeps the user in the editor instead of
   * bailing out to a failed run.
   */
  commitError() {
    for (const t of this.tokens) {
      if (t.validate) {
        const err = t.validate(t.value);
        if (err) return `${t.key}: ${err}`;
      }
      if (t.sourceToken && !SOURCES.some((s) => s.id === t.value)) {
        const near = SOURCES.filter((s) => s.id.startsWith(String(t.value)[0]));
        return `unknown source "${t.value}"` +
          (near.length ? ` — did you mean ${near.map((s) => s.id).join(' / ')}?`
                       : ` — try ${SOURCES.map((s) => s.id).join(', ')}`);
      }
    }
    return null;
  }

  backspace() {
    if (this.typing === null) return;
    this.typing = this.typing.slice(0, -1);
    this.menuOffset = 0;
    if (this.token.freeform) this._apply(this.typing);
  }

  // ── rendering ──────────────────────────────────────────────────────────

  /** The sentence, with the active token highlighted. */
  sentence() {
    let out = `${AMBER}${c.bold}download${c.reset} `;
    for (let i = 0; i < this.tokens.length; i++) {
      const t = this.tokens[i];
      if (i > 0 && t.label) out += `${c.dim}${t.label}${c.reset} `;
      const active = i === this.index;
      const val = String(t.value ?? '');
      out += active
        ? `${c.inverse}${CYAN}${c.bold} ${val || '…'} ${c.reset}`
        : `${CYAN}${val || c.dim + '…'}${c.reset}`;
      out += ' ';
    }
    return out;
  }

  render(menuHeight = 8) {
    const lines = [];
    lines.push('');
    lines.push('  ' + this.sentence());
    lines.push('');

    const opts = this.options();
    const t = this.token;

    const title = this.typing !== null
      ? `type to filter — ⏎ to accept "${this.typing}"`
      : (t.hint || `choose a ${t.key}`);

    lines.push(`  ${c.dim}┌ ${c.bold}${title}${c.reset}${c.dim} ${'─'.repeat(Math.max(2, 46 - sw(title)))}┐${c.reset}`);

    if (!opts.length) {
      lines.push(`  ${c.dim}│${c.reset} ${c.italic}${c.dim}no match — keep typing, ⏎ uses your text${c.reset}${' '.repeat(12)}${c.dim}│${c.reset}`);
    } else {
      const view = opts.slice(this.menuOffset, this.menuOffset + menuHeight);
      for (const o of view) {
        const sel = o === (this.typing ?? t.value);
        const row = sel
          ? `${c.bold}${CYAN}  › ${o}${c.reset}`
          : `${c.dim}    ${o}${c.reset}`;
        lines.push(`  ${c.dim}│${c.reset}${padEnd(row, 47)}${c.dim}│${c.reset}`);
      }
      if (opts.length > menuHeight) {
        lines.push(`  ${c.dim}│    · · · ${opts.length} options${' '.repeat(Math.max(0, 30))}│${c.reset}`);
      }
    }
    lines.push(`  ${c.dim}└${'─'.repeat(48)}┘${c.reset}`);
    lines.push('');

    if (this.error) {
      lines.push(`  ${c.bgRed}${c.bold}${c.white} ✖ ${this.error} ${c.reset}`);
    } else {
      lines.push(
        `  ${c.dim}←→${c.reset} move   ${c.dim}↑↓${c.reset} value   ` +
        `${c.dim}type${c.reset} custom   ${c.dim}⏎${c.reset} grab   ${c.dim}esc${c.reset} quit`,
      );
    }
    return lines;
  }
}

function padEnd(s, n) {
  const w = sw(s);
  return s + ' '.repeat(Math.max(0, n - w));
}


// ──────────────────────────────────────────────────────────────────
// src/cli.mjs
// ──────────────────────────────────────────────────────────────────
// wallgrab — bulk wallpaper downloader with an inline sentence editor.


const VERSION = '1.0.0';
// ─────────────────────────────────────────────────────────────── arg parsing

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help' || a === '-h') out.help = true;
    else if (a === '--version' || a === '-v') out.version = true;
    else if (a === '--yes' || a === '-y') out.yes = true;
    else if (a === '--sources') out.sources = true;
    else if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next !== undefined && !next.startsWith('--')) { out[key] = next; i++; }
      else out[key] = true;
    } else out._.push(a);
  }
  return out;
}

function help() {
  const themes = Object.keys(THEME).join(' · ');
  return `${banner('ocean')}
${rule('─', 74, 'ocean')}

  ${c.bold}Usage${c.reset}
    wallgrab                          interactive sentence editor
    wallgrab ${c.dim}[flags]${c.reset} --yes           non-interactive, for scripts & CI

  ${c.bold}Flags${c.reset}
    ${CYAN}--source${c.reset} <id>        ${c.dim}wallhaven · unsplash · nasa · openverse · pexels${c.reset}
                         ${c.dim}pixabay · artic · met · picsum · github · reddit${c.reset}
    ${CYAN}--query${c.reset} <text>       search terms              ${c.dim}(default: minimal)${c.reset}
    ${CYAN}--count${c.reset} <n>          how many to fetch         ${c.dim}(default: 100)${c.reset}
    ${CYAN}--dir${c.reset} <path>         output folder             ${c.dim}(default: ./wallpapers)${c.reset}
    ${CYAN}--format${c.reset} <ext>       jpg png webp gif avif any ${c.dim}(default: any)${c.reset}
    ${CYAN}--jobs${c.reset} <n>           parallel downloads        ${c.dim}(default: 6)${c.reset}
    ${CYAN}--theme${c.reset} <name>       ${themes}
    ${CYAN}--yes${c.reset}, -y            skip the editor, run immediately
    ${CYAN}--sources${c.reset}            list every source and exit
    ${CYAN}--version${c.reset}, -v        print version
    ${CYAN}--help${c.reset}, -h           this screen

  ${c.bold}Source-specific flags${c.reset} ${c.dim}(only read when that source is selected)${c.reset}
    wallhaven  --resolution 2560x1440 --sort favorites --ratio 16x9
               --color 333399 --category general
    github     --repo dharmx/walls --filter abstract --pick largest
    reddit     --subreddit MinimalWallpaper --window year
    picsum     --size 3840x2160 --mode grayscale
    artic      --iiifWidth 3000px
    openverse  --license cc0 --size large
    unsplash   --orientation landscape --sort latest
    pexels     --orientation landscape --color blue
    pixabay    --imageType illustration --orientation horizontal

  ${c.bold}API keys${c.reset} ${c.dim}(only unsplash, pexels and pixabay need one)${c.reset}
    ${AMBER}export${c.reset} UNSPLASH_ACCESS_KEY=xxx    ${c.dim}https://unsplash.com/developers${c.reset}
    ${AMBER}export${c.reset} PEXELS_API_KEY=xxx         ${c.dim}https://www.pexels.com/api/${c.reset}
    ${AMBER}export${c.reset} PIXABAY_API_KEY=xxx        ${c.dim}https://pixabay.com/api/docs/${c.reset}

  ${c.bold}In the editor${c.reset}
    ${CYAN}← →${c.reset}  move between the highlighted words
    ${CYAN}↑ ↓${c.reset}  cycle that word's values
    ${CYAN}type${c.reset} filter the list, or enter your own value
    ${CYAN}⏎${c.reset}    run it      ${CYAN}esc${c.reset} quit      ${CYAN}ctrl+c${c.reset} abort a download
`;
}

function listSources() {
  const rows = SOURCES.map((s) => {
    const key = s.keyEnv ? `${c.yellow}needs ${s.keyEnv}${c.reset}` : `${c.green}no key${c.reset}`;
    return `  ${CYAN}${padStr(s.id, 11)}${c.reset} ${padStr(s.name, 24)} ${key}  ${c.dim}${s.blurb}${c.reset}`;
  });
  return `${banner('grape')}\n${rows.join('\n')}\n`;
}

const padStr = (s, n) => s + ' '.repeat(Math.max(0, n - s.length));

// ─────────────────────────────────────────────────────────────── editor loop

async function runEditor(theme) {
  const editor = new SentenceEditor('wallhaven');
  process.stdout.write(hideCursor);

  let lines = editor.render();
  const draw = () => {
    if (lines.length) {
      process.stdout.write(cursorUp(lines.length) + lines.map(() => clearLine).join(cursorUp(1)));
      process.stdout.write(cursorUp(lines.length));
      for (let i = 0; i < lines.length; i++) process.stdout.write(clearLine + '\n');
      process.stdout.write(cursorUp(lines.length));
    }
    lines = editor.render();
    process.stdout.write(lines.join('\n'));
  };

  draw();

  return new Promise((resolve) => {
    const onData = (buf) => {
      const s = buf.toString();

      if (s === '\x03') { cleanup(); resolve(null); return; }        // ctrl+c
      if (s === '\x1b' && buf.length === 1) { cleanup(); resolve(null); return; } // esc

      if (s === '\x1b[D') { editor.move(-1); draw(); return; }       // ←
      if (s === '\x1b[C') { editor.move(1); draw(); return; }        // →
      if (s === '\x1b[A') { editor.cycle(-1); draw(); return; }      // ↑
      if (s === '\x1b[B') { editor.cycle(1); draw(); return; }       // ↓
      if (s === '\t') { editor.move(1); draw(); return; }

      if (s === '\r' || s === '\n') {
        editor.cancelTyping();
        const err = editor.commitError();
        if (err) { editor.error = err; draw(); return; }
        cleanup();
        resolve(editor.values);
        return;
      }
      if (s === '\x7f' || s === '\b') { editor.backspace(); draw(); return; }
      if (s === '\x15') { editor.clearTyping(); draw(); return; }    // ctrl+u

      // printable characters start/extend the filter
      for (const ch of s) {
        if (ch >= ' ' && ch.charCodeAt(0) < 127) editor.typeChar(ch);
      }
      draw();
    };

    const cleanup = () => {
      process.stdin.removeListener('data', onData);
      if (process.stdin.isTTY) process.stdin.setRawMode(false);
      process.stdin.pause();
      process.stdout.write(showCursor + '\n');
    };

    if (process.stdin.isTTY) process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.on('data', onData);
  });
}

// ────────────────────────────────────────────────────────────────── running

async function resolveKey(src) {
  if (!src.keyEnv) return { ok: true };
  const key = process.env[src.keyEnv];
  if (key) return { ok: true, key };
  return {
    ok: false,
    msg: `${src.name} needs a free API key.\n` +
         `    ${AMBER}export ${src.keyEnv}=your_key${c.reset}\n` +
         `    ${c.dim}${src.keyHint}${c.reset}\n\n` +
         `    Or pick a no-key source: ${SOURCES.filter((s) => !s.keyEnv).map((s) => s.id).join(', ')}`,
  };
}

async function execute(values, jobs) {
  const src = byId(values.source);
  if (!src) { console.log(`${c.red}unknown source: ${values.source}${c.reset}`); return 1; }

  const keyRes = await resolveKey(src);
  if (!keyRes.ok) { console.log('\n' + keyRes.msg + '\n'); return 1; }

  const params = {
    query: values.query,
    count: Math.max(1, parseInt(values.count, 10) || 100),
    ...values,
  };

  console.log(`\n  ${CYAN}⟡${c.reset} searching ${c.bold}${src.name}${c.reset} for ${c.bold}"${params.query}"${c.reset} ${c.dim}(wanting ${params.count})${c.reset}\n`);

  let items;
  try {
    items = await src.search(params, keyRes.key);
  } catch (e) {
    console.log(`  ${c.bgRed}${c.bold}${c.white} ✖ ${c.reset} ${e.message}\n`);
    if (/HTML instead of JSON|403|429/.test(e.message)) {
      console.log(`  ${c.dim}That usually means the source rate-limited this IP. Wait a few`);
      console.log(`  minutes, lower --count, or try another source.${c.reset}\n`);
    }
    return 1;
  }

  if (!items?.length) {
    console.log(`  ${c.yellow}no results for that query — try different terms${c.reset}\n`);
    return 1;
  }
  console.log(`  ${c.green}✓${c.reset} found ${c.bold}${items.length}${c.reset} images\n`);

  // progress line
  let tick = 0;
  const onProgress = (st) => {
    const pct = st.total ? st.done / st.total : 0;
    const rate = st.bytes / Math.max(0.001, (Date.now() - st.startedAt) / 1000);
    const eta = rate > 0 ? (st.total - st.done) * (st.bytes / Math.max(1, st.done)) / rate : 0;
    const spin = SPINNER[tick++ % SPINNER.length];
    process.stdout.write(
      '\r' + clearLine +
      `  ${CYAN}${spin}${c.reset} ${bar(pct, 26)} ` +
      `${c.bold}${String(st.done).padStart(4)}/${st.total}${c.reset} ` +
      `${c.green}${st.ok}✓${c.reset} ${c.dim}${st.skipped}–${c.reset} ${c.red}${st.failed}✖${c.reset} ` +
      `${AMBER}${humanBytes(st.bytes)}${c.reset} ${c.dim}@ ${humanBytes(rate)}/s · eta ${humanTime(eta)}${c.reset}`,
    );
  };

  const st = await downloadAll(items, {
    dir: values.dir,
    format: values.format || 'any',
    concurrency: jobs,
    onProgress,
  });
  process.stdout.write('\n\n');

  const lines = [
    `${c.green}${c.bold}${st.ok}${c.reset} wallpapers saved  ${c.dim}(${humanBytes(st.bytes)})${c.reset}`,
    st.skipped ? `${c.yellow}${st.skipped}${c.reset} skipped  ${c.dim}(already there, or wrong format)${c.reset}` : null,
    st.failed ? `${c.red}${st.failed}${c.reset} failed` : null,
    `${c.dim}${st.elapsed.toFixed(1)}s · ${values.dir}${c.reset}`,
  ].filter(Boolean);

  console.log(box(lines, 'done', 'mint'));

  if (st.errors.length) {
    console.log(`\n  ${c.dim}first few problems:${c.reset}`);
    for (const e of st.errors.slice(0, 5)) {
      console.log(`    ${c.dim}·${c.reset} ${e.name} ${c.dim}— ${e.why}${c.reset}`);
    }
  }
  console.log(`\n  ${gradient('grab more →', ['#11998e', '#38ef7d'])} ${c.dim}run wallgrab again${c.reset}\n`);
  return 0;
}

// ────────────────────────────────────────────────────────────────────── main

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const theme = args.theme && THEME[args.theme] ? args.theme : 'sunset';

  if (args.help) { console.log(help()); return 0; }
  if (args.version) { console.log(`wallgrab ${VERSION}`); return 0; }
  if (args.sources) { console.log(listSources()); return 0; }

  // non-interactive: any explicit --source runs straight away
  if (args.yes || args.source) {
    const src = byId(args.source || 'wallhaven');
    if (!src) { console.log(`${c.red}unknown source "${args.source}"${c.reset}\nTry: ${SOURCES.map((s) => s.id).join(', ')}`); return 1; }
    const values = {
      source: src.id,
      count: String(args.count ?? src.defaults.count),
      query: args.query ?? src.defaults.query,
      format: args.format ?? 'any',
      dir: args.dir ?? './wallpapers',
    };
    for (const extra of src.extra) {
      if (args[extra.key] !== undefined) values[extra.key] = args[extra.key];
      else values[extra.key] = extra.value;
    }
    return execute(values, parseInt(args.jobs, 10) || 6);
  }

  process.stdout.write(banner(theme));
  process.stdout.write('\n' + rule('─', 74, theme) + '\n');

  const values = await runEditor(theme);
  if (!values) { console.log(`  ${c.dim}nothing grabbed — see you next time${c.reset}\n`); return 0; }

  return execute(values, parseInt(args.jobs, 10) || 6);
}

const code = await main().catch((e) => {
  console.error(`\n${c.bgRed}${c.bold}${c.white} ✖ ${c.reset} ${e.stack || e.message}\n`);
  return 1;
});
process.stdout.write(showCursor);
process.exit(code);

