#!/usr/bin/env node
//
// wallgrab — bulk wallpaper downloader. Single-file build.
//
// Generated by scripts/build-standalone.mjs from src/. Do not edit by hand;
// change the sources and rebuild. Zero dependencies, Node 18+.
//
import { mkdir, writeFile, stat, readFile, rename, rm, readdir } from 'node:fs/promises';
import { join, resolve, dirname, isAbsolute } from 'node:path';
import { homedir, platform } from 'node:os';
import { existsSync, statSync } from 'node:fs';
import process from 'node:process';

// ──────────────────────────────────────────────────────────────────
// src/ansi.mjs
// ──────────────────────────────────────────────────────────────────
// Terminal primitives: colour, cursor, gradients. No dependencies.

const esc = (s) => `\x1b[${s}`;

const c = {
  reset: esc('0m'),
  bold: esc('1m'),
  dim: esc('2m'),
  italic: esc('3m'),
  underline: esc('4m'),
  inverse: esc('7m'),

  black: esc('30m'),
  red: esc('31m'),
  green: esc('32m'),
  yellow: esc('33m'),
  blue: esc('34m'),
  magenta: esc('35m'),
  cyan: esc('36m'),
  white: esc('37m'),
  gray: esc('90m'),

  bgBlack: esc('40m'),
  bgRed: esc('41m'),
  bgGreen: esc('42m'),
  bgYellow: esc('43m'),
  bgBlue: esc('44m'),
  bgMagenta: esc('45m'),
  bgCyan: esc('46m'),
};

const clearLine = esc('2K');
const cursorUp = (n = 1) => esc(`${n}A`);
const cursorDown = (n = 1) => esc(`${n}B`);
const cursorTo = (col) => esc(`${col + 1}G`);
const hideCursor = esc('?25l');
const showCursor = esc('?25h');
const clearScreen = esc('2J') + esc('H');
const saveCursor = esc('s');
const restoreCursor = esc('u');

/** True when the terminal is very unlikely to render ANSI properly. */
const supportsColor = () => {
  if (process.env.NO_COLOR) return false;
  if (process.env.FORCE_COLOR) return true;
  if (process.platform === 'win32') return true; // Windows Terminal / conhost on Win10+
  const term = process.env.TERM || '';
  if (term === 'dumb') return false;
  return Boolean(process.stdout.isTTY);
};

/** True when we can use 24-bit colour (used for the gradient banner). */
const supportsTrueColor = () => {
  if (!supportsColor()) return false;
  const term = process.env.TERM || '';
  const ci = process.env.CI ? true : false;
  return /truecolor|24bit/i.test(process.env.COLORTERM || '') ||
    /xterm-256|alacritty|kitty|wezterm|ghostty|iterm|tmux/i.test(term) ||
    ci || process.platform === 'win32';
};

// Theme accents, resolved once at load.
const CYAN = supportsTrueColor() ? esc('38;2;0;198;255m') : c.cyan;
const AMBER = supportsTrueColor() ? esc('38;2;255;195;113m') : c.yellow;
const GREEN = supportsTrueColor() ? esc('38;2;56;239;125m') : c.green;

const hexToRgb = (hex) => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
];

const rgbFg = ([r, g, b]) => esc(`38;2;${r};${g};${b}m`);
const rgbBg = ([r, g, b]) => esc(`48;2;${r};${g};${b}m`);

const lerp = (a, b, t) => Math.round(a + (b - a) * t);
const mix = (from, to, t) => [
  lerp(from[0], to[0], t),
  lerp(from[1], to[1], t),
  lerp(from[2], to[2], t),
];

/**
 * Paint every visible column of `text` with a horizontal gradient.
 * Multiline strings keep the same gradient phase on every line so the
 * banner reads as one continuous sweep.
 */
function gradient(text, stops) {
  if (!supportsTrueColor()) return text;
  const rgbStops = stops.map(hexToRgb);
  const lines = text.split('\n');
  const width = Math.max(...lines.map((l) => [...l].length));

  return lines
    .map((line) => {
      let col = 0;
      let out = '';
      for (const ch of line) {
        if (ch === ' ') {
          out += ' ';
          col++;
          continue;
        }
        const t = width <= 1 ? 0 : col / (width - 1);
        out += rgbFg(sample(rgbStops, t)) + ch + c.reset;
        col++;
      }
      return out;
    })
    .join('\n');
}

function sample(stops, t) {
  if (stops.length === 1) return stops[0];
  const scaled = t * (stops.length - 1);
  const i = Math.min(Math.floor(scaled), stops.length - 2);
  return mix(stops[i], stops[i + 1], scaled - i);
}

/** Vertical variant — used for the sidebar rules and the progress bar. */
function gradientRows(rows, stops) {
  return rows.map((r, i) => {
    const t = rows.length <= 1 ? 0 : i / (rows.length - 1);
    if (!supportsTrueColor()) return r;
    return rgbFg(sample(stops.map(hexToRgb), t)) + r + c.reset;
  });
}

/** Strip ANSI so we can measure real display width. */
// eslint-disable-next-line no-control-regex
const strip = (s) => s.replace(/\x1b\[[0-9;?]*[a-zA-Z]/g, '');
const width = (s) => [...strip(s)].length;

/** Bar like ▓▓▓▓░░░░ for a 0..1 fraction. */
function bar(fraction, size = 24) {
  const f = Math.max(0, Math.min(1, fraction));
  const filled = Math.round(f * size);
  return '█'.repeat(filled) + '░'.repeat(size - filled);
}

const pad = (s, n, align = 'left') => {
  const w = width(s);
  if (w >= n) return s;
  const gap = ' '.repeat(n - w);
  if (align === 'right') return gap + s;
  if (align === 'center') {
    const l = Math.floor((n - w) / 2);
    return ' '.repeat(l) + s + ' '.repeat(n - w - l);
  }
  return s + gap;
};


// import aliases re-bound by the bundler
const sw = width;


// ──────────────────────────────────────────────────────────────────
// src/sources.mjs
// ──────────────────────────────────────────────────────────────────
// Twelve wallpaper sources behind one interface.
//
// Each source returns [{ url, name, ext, width, height, credit }].
// `keyEnv` marks sources that need a free API key; the CLI asks for it and
// explains where to get one, rather than failing with a 401.

const JSON_HEADERS = { Accept: 'application/json', 'User-Agent': UA() };

function UA() {
  return 'wallgrab/1.0 (+https://github.com/bhavyam2468/get-wallpapers)';
}

async function getJSON(url, headers = {}) {
  const res = await fetch(url, { headers: { ...JSON_HEADERS, ...headers }, redirect: 'follow' });
  if (!res.ok) {
    const body = (await res.text().catch(() => '')).slice(0, 180).replace(/\s+/g, ' ');
    throw new Error(`HTTP ${res.status} ${res.statusText}${body ? ` — ${body}` : ''}`);
  }
  const text = await res.text();
  if (text.trimStart().startsWith('<')) {
    throw new Error('server answered with HTML instead of JSON (rate limited or blocked?)');
  }
  return JSON.parse(text);
}

const extFrom = (url, fallback = 'jpg') => {
  try {
    const p = new URL(url).pathname;
    const m = p.match(/\.(jpe?g|png|webp|gif|avif|bmp)$/i);
    return m ? m[1].toLowerCase().replace('jpeg', 'jpg') : fallback;
  } catch {
    return fallback;
  }
};

const safeFile = (s, max = 70) =>
  (s || 'wallpaper')
    .replace(/[^\w.\- ]+/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, max) || 'wallpaper';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Fetch pages until we have `count` items. Handles per-API page caps. */
async function paginate(pageSize, count, fetchPage, delay = 220) {
  const out = [];
  for (let page = 1; out.length < count; page++) {
    const items = await fetchPage(page, pageSize);
    if (!items || items.length === 0) break;
    out.push(...items);
    if (items.length < pageSize) break; // last page
    if (out.length < count) await sleep(delay);
  }
  return out.slice(0, count);
}

// ─────────────────────────────────────────────────────────────── wallhaven

const wallhaven = {
  id: 'wallhaven',
  name: 'Wallhaven',
  blurb: 'the community giant — 19k+ minimal, 12k+ abstract, full-res originals',
  keyEnv: null,
  defaults: { query: 'minimal', count: 100 },
  extra: [
    {
      key: 'resolution',
      label: 'at',
      value: '2560x1440',
      options: ['any', '1920x1080', '2560x1440', '3440x1440', '3840x2160', '5120x2880', '7680x4320'],
      hint: 'minimum resolution',
    },
    {
      key: 'sort',
      label: 'sorted by',
      value: 'favorites',
      options: ['favorites', 'toplist', 'date_added', 'views', 'random', 'relevance'],
    },
    {
      key: 'ratio',
      label: 'shaped',
      value: '16x9',
      options: ['any', '16x9', '16x10', '21x9', '32x9', '9x16', '4x3', '1x1'],
    },
    {
      key: 'color',
      label: 'tinted',
      value: 'any',
      options: ['any', '660000', '990000', 'cc0000', 'cc3333', 'ea4c88', '993399',
        '663399', '333399', '0066cc', '0099cc', '66cccc', '77cc33', '669900',
        '336600', '666600', '999900', 'cccc33', 'ffff00', 'ffcc33', 'ff9900',
        'ff6600', 'cc6633', '996633', '663300', '000000', '999999', 'cccccc',
        '424153', 'ffffff'],
      hint: 'dominant colour hex',
    },
    {
      key: 'category',
      label: 'kind',
      value: 'general',
      options: ['general', 'anime', 'people', 'general+anime', 'all'],
    },
  ],
  async search({ query, count, resolution, sort, ratio, color, category }) {
    const catMap = {
      general: '100', anime: '010', people: '001',
      'general+anime': '110', all: '111',
    };
    return paginate(24, count, async (page) => {
      const p = new URLSearchParams({
        q: query, page: String(page), purity: '100',
        categories: catMap[category] || '111',
        sorting: sort || 'favorites', order: 'desc',
      });
      if (resolution && resolution !== 'any') p.set('atleast', resolution);
      if (ratio && ratio !== 'any') p.set('ratios', ratio);
      if (color && color !== 'any') p.set('colors', color.replace('#', ''));

      const data = await getJSON(`https://wallhaven.cc/api/v1/search?${p}`);
      return (data.data || []).map((w) => {
        const [width, height] = (w.resolution || '0x0').split('x').map(Number);
        return {
          url: w.path,
          name: `wallhaven_${w.id}_${w.resolution}`,
          ext: extFrom(w.path),
          width, height,
          credit: `wallhaven · ${w.id}`,
        };
      });
    });
  },
};

// ─────────────────────────────────────────────────────────────────── nasa

const nasa = {
  id: 'nasa',
  name: 'NASA',
  blurb: 'public-domain deep space, ultra-high resolution, no key needed',
  keyEnv: null,
  defaults: { query: 'nebula', count: 60 },
  extra: [],
  async search({ query, count }) {
    return paginate(100, count, async (page) => {
      const p = new URLSearchParams({
        q: query, media_type: 'image', page: String(page), per_page: '100',
      });
      const data = await getJSON(`https://images-api.nasa.gov/search?${p}`);
      return (data.collection?.items || [])
        .map((it) => {
          const link = it.links?.[0]?.href;
          if (!link) return null;
          // prefer the original, then large, then whatever we got
          const orig = link.replace(/~(large|medium|small|thumb)\./, '~orig.');
          return {
            url: orig,
            name: `nasa_${safeFile(it.data?.[0]?.nasa_id || it.data?.[0]?.title, 60)}`,
            ext: extFrom(link),
            width: 0, height: 0,
            credit: `NASA · ${it.data?.[0]?.photographer || 'public domain'}`,
          };
        })
        .filter(Boolean);
    });
  },
};

// ───────────────────────────────────────────────────────────────── openverse

const openverse = {
  id: 'openverse',
  name: 'Openverse',
  blurb: '600M+ openly-licensed images, filtered by license for you',
  keyEnv: null,
  defaults: { query: 'abstract', count: 60 },
  extra: [
    {
      key: 'license',
      label: 'licensed',
      value: 'any',
      options: ['any', 'all-cc', 'cc0', 'by', 'by-sa', 'public-domain-mark'],
    },
    {
      key: 'size',
      label: 'sized',
      value: 'any',
      options: ['any', 'small', 'medium', 'large'],
    },
  ],
  async search({ query, count, license, size }) {
    return paginate(50, count, async (page) => {
      const p = new URLSearchParams({ q: query, page: String(page), page_size: '50' });
      const licMap = {
        'all-cc': 'cc0,by,by-sa,by-nd,by-nc,by-nc-sa,by-nc-nd',
        'public-domain-mark': 'public-domain-mark',
      };
      if (license && license !== 'any') p.set('license', licMap[license] || license);
      if (size && size !== 'any') p.set('size', size);

      const data = await getJSON(`https://api.openverse.org/v1/images/?${p}`);
      return (data.results || []).map((r) => ({
        url: r.url,
        name: `openverse_${safeFile(r.title || r.id, 60)}`,
        ext: extFrom(r.url),
        width: r.width || 0, height: r.height || 0,
        credit: `${r.license?.toUpperCase()} · ${r.creator || 'unknown'}`,
      }));
    });
  },
};

// ───────────────────────────────────────────────────────────────────── met

const met = {
  id: 'met',
  name: 'The Met',
  blurb: 'Metropolitan Museum highlights — paintings as maximalist wallpapers',
  keyEnv: null,
  defaults: { query: 'abstract', count: 40 },
  extra: [],
  async search({ query, count }) {
    const q = new URLSearchParams({ q: query, isHighlight: 'true', hasImages: 'true' });
    const found = await getJSON(`https://collectionapi.metmuseum.org/public/collection/v1/search?${q}`);
    const ids = (found.objectIDs || []).slice(0, Math.min(count * 2, 250));
    if (!ids.length) return [];

    const out = [];
    for (const id of ids) {
      if (out.length >= count) break;
      try {
        const o = await getJSON(
          `https://collectionapi.metmuseum.org/public/collection/v1/objects/${id}`,
        );
        if (!o.primaryImage) continue;
        out.push({
          url: o.primaryImage,
          name: `met_${safeFile(o.title || String(id), 60)}`,
          ext: extFrom(o.primaryImage),
          width: 0, height: 0,
          credit: `The Met · ${o.artistDisplayName || 'unknown'} · public domain`,
        });
      } catch { /* skip a single bad record */ }
      await sleep(60);
    }
    return out;
  },
};

// ─────────────────────────────────────────────────────────────────── artic

const artic = {
  id: 'artic',
  name: 'Art Institute of Chicago',
  blurb: '132k+ works served over IIIF, any resolution you ask for',
  keyEnv: null,
  defaults: { query: 'abstract', count: 40 },
  extra: [
    {
      key: 'iiifWidth',
      label: 'rendered at',
      value: '2000px',
      options: ['843px', '1686px', '2000px', '3000px', 'full'],
      hint: 'IIIF render width',
    },
  ],
  async search({ query, count, iiifWidth }) {
    const w = (iiifWidth || '2000px').replace('px', '');
    return paginate(50, count, async (page) => {
      const p = new URLSearchParams({
        q: query, limit: '50', page: String(page),
        fields: 'id,title,image_id,artist_display,date_display',
      });
      const data = await getJSON(`https://api.artic.edu/api/v1/artworks/search?${p}`);
      return (data.data || [])
        .filter((a) => a.image_id)
        .map((a) => ({
          url: `https://www.artic.edu/iiif/2/${a.image_id}/full/,${w},/0/default.jpg`,
          name: `artic_${safeFile(a.title || String(a.id), 60)}`,
          ext: 'jpg',
          width: 0, height: 0,
          credit: `Art Institute of Chicago · ${a.artist_display || 'unknown'}`,
        }));
    });
  },
};

// ────────────────────────────────────────────────────────────────── picsum

const picsum = {
  id: 'picsum',
  name: 'Lorem Picsum',
  blurb: 'infinite random photography, rendered to any size you want',
  keyEnv: null,
  defaults: { query: 'any', count: 50 },
  extra: [
    {
      key: 'size',
      label: 'at',
      value: '3840x2160',
      options: ['1920x1080', '2560x1440', '3840x2160', '5120x2880', '1080x1920', '1440x2560'],
      hint: 'rendered size',
    },
    {
      key: 'mode',
      label: 'style',
      value: 'color',
      options: ['color', 'grayscale', 'blurred'],
    },
  ],
  async search({ count, size, mode }) {
    const [w, h] = (size || '3840x2160').split('x');
    const pool = [];
    for (let page = 1; pool.length < count * 2 && page <= 6; page++) {
      const list = await getJSON(`https://picsum.photos/v2/list?page=${page}&limit=100`);
      if (!Array.isArray(list) || !list.length) break;
      pool.push(...list);
      await sleep(150);
    }
    return pool.slice(0, count).map((img) => {
      let u = `https://picsum.photos/id/${img.id}/${w}/${h}`;
      if (mode === 'grayscale') u += '?grayscale';
      if (mode === 'blurred') u += '?blur=2';
      return {
        url: u,
        name: `picsum_${img.id}_${w}x${h}${mode === 'grayscale' ? '_gray' : ''}`,
        ext: 'jpg',
        width: +w, height: +h,
        credit: `Lorem Picsum · ${img.author}`,
      };
    });
  },
};

// ────────────────────────────────────────────────────────────────── github

const github = {
  id: 'github',
  name: 'GitHub collection',
  blurb: 'curated wallpaper repos — hundreds of images, no git clone needed',
  keyEnv: null,
  defaults: { query: 'AngelJumbo/gruvbox-wallpapers', count: 150 },
  extra: [
    {
      key: 'repo',
      label: 'repo',
      value: 'AngelJumbo/gruvbox-wallpapers',
      options: [
        'AngelJumbo/gruvbox-wallpapers', 'D3Ext/aesthetic-wallpapers',
        'linuxdotexe/nordic-wallpapers', 'dharmx/walls', 'rose-pine/wallpapers',
        'makccr/wallpapers', 'vyrx-dev/Wallpapers', 'elementary/wallpapers',
        'Narmis-E/onedark-wallpapers', 'vinceliuice/WhiteSur-wallpapers',
      ],
      hint: 'owner/name — type your own',
      freeform: true,
    },
    {
      key: 'filter',
      label: 'matching',
      value: 'any',
      options: ['any', 'abstract', 'minimal', 'dark', '4k', 'nature', 'gradient'],
      hint: 'substring of the file path',
    },
    {
      key: 'pick',
      label: 'picking',
      value: 'largest',
      options: ['largest', 'first', 'random'],
    },
  ],
  async search({ count, repo, filter, pick }) {
    const r = (repo || '').trim().replace(/^https?:\/\/github\.com\//, '').replace(/\.git$/, '');
    if (!/^[\w.-]+\/[\w.-]+$/.test(r)) {
      throw new Error(`repo "${r}" should look like owner/name, e.g. dharmx/walls`);
    }
    const meta = await getJSON(`https://api.github.com/repos/${r}`);
    const branch = meta.default_branch || 'main';
    const tree = await getJSON(
      `https://api.github.com/repos/${r}/git/trees/${branch}?recursive=1`,
    );

    const IMG = /\.(jpe?g|png|webp|gif|avif|bmp)$/i;
    let files = (tree.tree || [])
      .filter((e) => e.type === 'blob' && IMG.test(e.path) && (e.size || 0) > 100 * 1024)
      .filter((e) => !filter || filter === 'any' || e.path.toLowerCase().includes(filter.toLowerCase()))
      .map((e) => ({ path: e.path, size: e.size || 0 }));

    if (tree.truncated) {
      throw new Error(
        `GitHub truncated the file list for ${r} — the repo is too big. ` +
        `Try a narrower --filter or a smaller repo.`,
      );
    }
    if (!files.length) throw new Error(`no images matched in ${r}`);

    if (pick === 'largest') files.sort((a, b) => b.size - a.size);
    if (pick === 'random') files.sort(() => Math.random() - 0.5);

    return files.slice(0, count).map((f) => ({
      url: `https://raw.githubusercontent.com/${r}/${branch}/${encodeURI(f.path).replace(/#/g, '%23')}`,
      name: `${safeFile(f.path.split('/').pop().replace(IMG, ''), 60)}`,
      ext: (f.path.match(IMG) || ['.jpg'])[0].slice(1).toLowerCase().replace('jpeg', 'jpg'),
      width: 0, height: 0,
      credit: `github · ${r}`,
    }));
  },
};

// ───────────────────────────────────────────────────────────────── reddit

const reddit = {
  id: 'reddit',
  name: 'Reddit',
  blurb: 'top posts from wallpaper subreddits (can be blocked from datacenter IPs)',
  keyEnv: null,
  defaults: { query: 'wallpaper', count: 100 },
  extra: [
    {
      key: 'subreddit',
      label: 'from r/',
      value: 'wallpaper',
      options: ['wallpaper', 'wallpapers', 'MinimalWallpaper', 'WidescreenWallpaper',
        'Amoledbackgrounds', 'EarthPorn', 'SpacePorn', 'ImaginaryLandscapes',
        'CyberpunkWallpapers', 'Animewallpaper', 'WallpaperRequests'],
      freeform: true,
    },
    {
      key: 'window',
      label: 'top of',
      value: 'year',
      options: ['hour', 'day', 'week', 'month', 'year', 'all'],
    },
  ],
  async search({ count, subreddit, window: win }) {
    const sub = (subreddit || 'wallpaper').replace(/^r\//, '');
    let after = null;
    const out = [];
    while (out.length < count) {
      const p = new URLSearchParams({ t: win || 'year', limit: '100', raw_json: '1' });
      if (after) p.set('after', after);
      const data = await getJSON(`https://www.reddit.com/r/${sub}/top.json?${p}`);
      const kids = data.data?.children || [];
      if (!kids.length) break;
      for (const k of kids) {
        const d = k.data;
        if (d.over_18 || d.stickied) continue;
        let url = d.preview?.images?.[0]?.source?.url?.replace(/&amp;/g, '&');
        if (!url && /\.(jpe?g|png|webp)$/i.test(d.url || '')) url = d.url;
        if (!url || d.is_video || d.post_hint === 'hosted:video') continue;
        out.push({
          url,
          name: `reddit_${safeFile(d.title, 60)}_${d.id}`,
          ext: extFrom(url),
          width: d.preview?.images?.[0]?.source?.width || 0,
          height: d.preview?.images?.[0]?.source?.height || 0,
          credit: `r/${sub} · ${d.score} pts · u/${d.author}`,
        });
        if (out.length >= count) break;
      }
      after = data.data?.after;
      if (!after) break;
      await sleep(600);
    }
    return out.slice(0, count);
  },
};

// ─────────────────────────────────────────────────────────────── keyed ones

const unsplash = {
  id: 'unsplash',
  name: 'Unsplash',
  blurb: 'professional photography — the best minimal & abstract library',
  keyEnv: 'UNSPLASH_ACCESS_KEY',
  keyHint: 'free key → https://unsplash.com/developers (new "Demo" app, 50 req/hr)',
  defaults: { query: 'minimal', count: 90 },
  extra: [
    {
      key: 'orientation',
      label: 'oriented',
      value: 'landscape',
      options: ['landscape', 'portrait', 'squarish', 'any'],
    },
    {
      key: 'sort',
      label: 'sorted by',
      value: 'relevant',
      options: ['relevant', 'latest'],
    },
  ],
  async search({ query, count, orientation, sort }, key) {
    return paginate(30, count, async (page) => {
      const p = new URLSearchParams({ query, page: String(page), per_page: '30' });
      if (orientation && orientation !== 'any') p.set('orientation', orientation);
      if (sort) p.set('order_by', sort);
      const data = await getJSON(`https://api.unsplash.com/search/photos?${p}`, {
        Authorization: `Client-ID ${key}`,
        'Accept-Version': 'v1',
      });
      return (data.results || []).map((r) => ({
        url: `${r.urls.raw}&fm=jpg&q=85`,
        name: `unsplash_${safeFile(r.slug || r.id, 60)}`,
        ext: 'jpg',
        width: r.width || 0, height: r.height || 0,
        credit: `Unsplash · ${r.user?.name || 'unknown'} · unsplash.com/license`,
      }));
    }, 1200); // demo tier is 50 req/hr — go slow
  },
};

const pexels = {
  id: 'pexels',
  name: 'Pexels',
  blurb: 'editorial-quality stock, strong on minimal & architecture',
  keyEnv: 'PEXELS_API_KEY',
  keyHint: 'free key → https://www.pexels.com/api/ (200 req/hr)',
  defaults: { query: 'minimalist', count: 100 },
  extra: [
    {
      key: 'orientation',
      label: 'oriented',
      value: 'landscape',
      options: ['landscape', 'portrait', 'square', 'any'],
    },
    {
      key: 'color',
      label: 'tinted',
      value: 'any',
      options: ['any', 'black_and_white', 'black', 'white', 'yellow', 'orange',
        'red', 'purple', 'magenta', 'green', 'teal', 'blue'],
    },
  ],
  async search({ query, count, orientation, color }, key) {
    return paginate(80, count, async (page) => {
      const p = new URLSearchParams({ query, page: String(page), per_page: '80' });
      if (orientation && orientation !== 'any') p.set('orientation', orientation);
      if (color && color !== 'any') p.set('color', color);
      const data = await getJSON(`https://api.pexels.com/v1/search?${p}`, {
        Authorization: key,
      });
      return (data.photos || []).map((r) => ({
        url: r.src.original,
        name: `pexels_${r.id}_${safeFile(r.alt, 50)}`,
        ext: extFrom(r.src.original),
        width: r.width || 0, height: r.height || 0,
        credit: `Pexels · ${r.photographer}`,
      }));
    }, 300);
  },
};

const pixabay = {
  id: 'pixabay',
  name: 'Pixabay',
  blurb: '4M+ photos, illustrations and vectors — best for graphic abstracts',
  keyEnv: 'PIXABAY_API_KEY',
  keyHint: 'free key → https://pixabay.com/api/docs/',
  defaults: { query: 'abstract', count: 100 },
  extra: [
    {
      key: 'imageType',
      label: 'kind',
      value: 'all',
      options: ['all', 'photo', 'illustration', 'vector'],
    },
    {
      key: 'orientation',
      label: 'oriented',
      value: 'horizontal',
      options: ['horizontal', 'vertical', 'any'],
    },
    {
      key: 'color',
      label: 'tinted',
      value: 'any',
      options: ['any', 'grayscale', 'transparent', 'red', 'orange', 'yellow',
        'green', 'turquoise', 'blue', 'lilac', 'pink', 'white', 'black', 'brown'],
    },
  ],
  async search({ query, count, imageType, orientation, color }, key) {
    return paginate(200, count, async (page) => {
      const p = new URLSearchParams({
        key, q: query, page: String(page), per_page: '200', safesearch: 'true',
      });
      if (imageType && imageType !== 'all') p.set('image_type', imageType);
      if (orientation && orientation !== 'any') p.set('orientation', orientation);
      if (color && color !== 'any') p.set('colors', color);
      const data = await getJSON(`https://pixabay.com/api/?${p}`);
      return (data.hits || []).map((r) => ({
        url: r.largeImageURL,
        name: `pixabay_${r.id}_${safeFile(r.tags?.split(',')[0], 50)}`,
        ext: extFrom(r.largeImageURL),
        width: r.imageWidth || 0, height: r.imageHeight || 0,
        credit: `Pixabay · ${r.user} · pixabay.com/service/license`,
      }));
    }, 300);
  },
};

const SOURCES = [
  wallhaven, unsplash, nasa, openverse, pexels, pixabay,
  artic, met, picsum, github, reddit,
];

const byId = (id) => SOURCES.find((s) => s.id === id);

/** Formats each source can actually produce, used to constrain the format token. */
const FORMATS = ['jpg', 'png', 'webp', 'gif', 'avif', 'any'];


// ──────────────────────────────────────────────────────────────────
// src/download.mjs
// ──────────────────────────────────────────────────────────────────
// Concurrent downloader with resume, magic-byte verification and live progress.


const MAGIC = {
  jpg: (b) => b[0] === 0xff && b[1] === 0xd8,
  png: (b) => b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e,
  gif: (b) => b[0] === 0x47 && b[1] === 0x49 && b[2] === 0x46,
  // WebP is a RIFF container: "RIFF" at 0..3, "WEBP" at 8..11
  webp: (b) => b.length > 11 &&
    b[0] === 0x52 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x46 &&
    b[8] === 0x57 && b[9] === 0x45 && b[10] === 0x42 && b[11] === 0x50,
  bmp: (b) => b[0] === 0x42 && b[1] === 0x4d,
  avif: (b) => b.length > 12 && b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70,
};

/** What format did the server *actually* send us? */
function sniff(buf) {
  for (const [k, test] of Object.entries(MAGIC)) if (test(buf)) return k;
  return null;
}

const uniq = (dir, base, ext) => {
  let name = `${base}.${ext}`;
  let i = 2;
  // cheap dedupe: stat is fast enough at these volumes
  const exists = async (n) => { try { await stat(join(dir, n)); return true; } catch { return false; } };
  return (async () => {
    while (await exists(name)) name = `${base}-${i++}.${ext}`;
    return name;
  })();
};

async function downloadAll(items, opts = {}) {
  const {
    dir = './wallpapers',
    format = 'any',
    concurrency = 6,
    retries = 3,
    onProgress = () => {},
    signal,
  } = opts;

  await mkdir(dir, { recursive: true });

  const state = {
    done: 0, ok: 0, skipped: 0, failed: 0, bytes: 0,
    total: items.length, current: '', startedAt: Date.now(), errors: [],
  };

  const queue = [...items];
  let cursor = 0;

  async function worker() {
    while (cursor < queue.length) {
      if (signal?.aborted) return;
      const item = queue[cursor++];
      state.current = item.name;
      try {
        const buf = await fetchWithRetry(item.url, retries);
        const actual = sniff(buf) || extOf(item.ext);

        // Honour the format token: keep only what really is that format.
        if (format !== 'any' && actual !== format) {
          state.skipped++;
          state.errors.push({ name: item.name, why: `is ${actual}, not ${format}` });
          continue;
        }

        const name = await uniq(dir, item.name, actual);
        await writeFile(join(dir, name), buf);
        state.ok++;
        state.bytes += buf.length;
      } catch (e) {
        state.failed++;
        state.errors.push({ name: item.name, why: e.message });
      } finally {
        state.done++;
        onProgress(state);
      }
    }
  }

  const workers = Array.from({ length: Math.max(1, concurrency) }, worker);
  await Promise.all(workers);
  state.elapsed = (Date.now() - state.startedAt) / 1000;
  return state;
}

const extOf = (e) => (e || 'jpg').toLowerCase().replace('jpeg', 'jpg');

async function fetchWithRetry(url, retries) {
  let last;
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url, {
        redirect: 'follow',
        headers: { 'User-Agent': 'wallgrab/1.0 (+https://github.com/bhavyam2468/get-wallpapers)' },
        signal: AbortSignal.timeout(60_000),
      });
      if (res.status === 429 || res.status >= 500) {
        throw new Error(`HTTP ${res.status}`);
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const buf = Buffer.from(await res.arrayBuffer());
      if (!buf.length) throw new Error('empty response');
      return buf;
    } catch (e) {
      last = e;
      await new Promise((r) => setTimeout(r, 400 * 2 ** i));
    }
  }
  throw last;
}

/** Bytes → human, and seconds → m:ss. */
const humanBytes = (n) => {
  if (n < 1024) return `${n} B`;
  const u = ['KB', 'MB', 'GB', 'TB'];
  let v = n / 1024, i = 0;
  while (v >= 1024 && i < u.length - 1) { v /= 1024; i++; }
  return `${v.toFixed(v < 10 ? 1 : 0)} ${u[i]}`;
};

const humanTime = (s) => {
  if (!isFinite(s) || s < 0) return '--:--';
  const m = Math.floor(s / 60);
  const sec = Math.floor(s % 60);
  return `${m}:${String(sec).padStart(2, '0')}`;
};


// ──────────────────────────────────────────────────────────────────
// src/banner.mjs
// ──────────────────────────────────────────────────────────────────
// ANSI-shadow glyphs, 8 columns wide, 6 rows tall.
const GLYPHS = {
  W: ['██╗    ██╗', '██║    ██║', '██║ █╗ ██║', '██║███╗██║', '╚███╔███╔╝', ' ╚══╝╚══╝ '],
  A: [' █████╗ ', '██╔══██╗', '███████║', '██╔══██║', '██║  ██║', '╚═╝  ╚═╝'],
  L: ['██╗     ', '██║     ', '██║     ', '██║     ', '███████╗', '╚══════╝'],
  G: [' ██████╗ ', '██╔════╝ ', '██║  ███╗', '██║   ██║', '╚██████╔╝', ' ╚═════╝ '],
  R: ['██████╗ ', '██╔══██╗', '██████╔╝', '██╔══██╗', '██║  ██║', '╚═╝  ╚═╝'],
  B: ['██████╗ ', '██╔══██╗', '██████╔╝', '██╔══██╗', '██████╔╝', '╚═════╝ '],
  ' ': ['        ', '        ', '        ', '        ', '        ', '        '],
};

const word = (w) => {
  const rows = ['', '', '', '', '', ''];
  for (const ch of w.toUpperCase()) {
    const g = GLYPHS[ch] || GLYPHS[' '];
    g.forEach((line, i) => { rows[i] += line; });
  }
  return rows;
};

const THEME = {
  sunset: ['#ff5f6d', '#ffc371'],
  ocean: ['#00c6ff', '#0072ff'],
  grape: ['#8e2de2', '#4a00e0'],
  mint: ['#11998e', '#38ef7d'],
  ember: ['#f7971e', '#ffd200'],
  rose: ['#ee9ca7', '#ff6a88'],
};

/**
 * Big gradient banner. Falls back to plain text on terminals without
 * truecolour so it never prints garbage.
 */
function banner(theme = 'sunset') {
  const rows = word('WALLGRAB');
  const stops = THEME[theme] || THEME.sunset;
  const art = supportsTrueColor() ? gradient(rows.join('\n'), stops) : rows.join('\n');

  const tagline = gradientRows([
    '  bulk wallpapers · eleven sources · zero dependencies',
    '  ↑↓ pick a value · ←→ move between them · ⏎ grab',
  ], stops);

  return `\n${art}\n\n${tagline.join('\n')}\n`;
}

/** Horizontal rule that matches the theme. */
function rule(char = '─', n = 74, theme = 'sunset') {
  const stops = THEME[theme] || THEME.sunset;
  const line = char.repeat(n);
  return supportsTrueColor() ? gradient(line, stops) : line;
}

/** Small framed box used for the completion summary. */
function box(lines, title, theme = 'sunset') {
  const inner = Math.max(
    ...lines.map((l) => [...strip(l)].length),
    title ? [...title].length + 4 : 0,
  );
  const w = Math.min(inner + 2, 72);
  const stops = THEME[theme] || THEME.sunset;
  const paint = (s) => (supportsTrueColor() ? gradient(s, stops) : s);

  const top = title
    ? `╭─${c.bold} ${title} ${c.reset}${paint('─'.repeat(Math.max(0, w - title.length - 4)))}╮`
    : paint(`╭${'─'.repeat(w)}╮`);
  const bottom = paint(`╰${'─'.repeat(w)}╯`);
  const body = lines.map(
    (l) => `${paint('│')} ${pad(strip(l), w - 2)} ${paint('│')}`,
  );
  return [top, ...body, bottom].join('\n');
}


const SPINNER = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];


// ──────────────────────────────────────────────────────────────────
// src/config.mjs
// ──────────────────────────────────────────────────────────────────
// Persistent preferences. First run remembers; every run after starts
// from where you left off. Keys are optional and only stored if present.


function configDir() {
  if (platform() === 'win32') {
    const base = process.env.APPDATA || join(homedir(), 'AppData', 'Roaming');
    return join(base, 'wallgrab');
  }
  const base = process.env.XDG_CONFIG_HOME || join(homedir(), '.config');
  return join(base, 'wallgrab');
}

const configPath = () => join(configDir(), 'config.json');

async function loadConfig() {
  try {
    const cfg = JSON.parse(await readFile(configPath(), 'utf8'));
    return cfg && typeof cfg === 'object' ? cfg : null;
  } catch {
    return null;
  }
}

/** Atomic write: temp file then rename, so a crash can't leave a torn config. */
async function saveConfig(cfg) {
  await mkdir(configDir(), { recursive: true });
  const tmp = configPath() + '.tmp';
  await writeFile(tmp, JSON.stringify({ ...cfg, updatedAt: new Date().toISOString() }, null, 2));
  await rename(tmp, configPath());
}

async function clearConfig() {
  try { await rm(configPath()); return true; } catch { return false; }
}

/** ghp_ab••••••cd — enough to recognise, not enough to leak. */
const mask = (k) =>
  (k && k.length > 8) ? `${k.slice(0, 6)}${'•'.repeat(6)}${k.slice(-2)}` : k ? '•'.repeat(8) : null;

/** The OS Downloads dir — the default base for the folder browser. */
const downloadsDir = () => join(homedir(), 'Downloads');

/** Where wallpapers land if you never touch the dir token. */
const defaultDir = () => join(downloadsDir(), 'wallgrab');


// ──────────────────────────────────────────────────────────────────
// src/tokens.mjs
// ──────────────────────────────────────────────────────────────────
// The inline editable command sentence.
//
//   download ⟨100⟩ ⟨minimal⟩ wallpapers from ⟨wallhaven⟩ as ⟨any⟩ into ⟨~/Downloads/wallgrab⟩
//
// ←/→ move between the ⟨tokens⟩ · ↑/↓ cycle values · type to filter/custom · ⏎ runs.
//
// The dir token additionally opens a folder browser (↓):
//   space enter folder · ⌫ parent · ⏎ select current · n new folder · ←/esc close
// and `e` toggles the config overlay.


const MENU_H = 8;

const DIR_OPTIONS = () => [defaultDir(), downloadsDir(), join(homedir(), 'Pictures')];

/** Build the token list for a source, keeping values the user already set. */
function buildTokens(sourceId, prev = {}) {
  const src = byId(sourceId);
  const tokens = [
    {
      key: 'count', label: 'download', value: prev.count ?? String(src?.defaults.count ?? 100),
      options: ['10', '25', '50', '100', '250', '500', '1000'],
      validate: (v) => (/^\d+$/.test(v) && +v > 0) ? null : 'needs a whole number',
    },
    {
      key: 'query', label: '', value: prev.query ?? src?.defaults.query ?? 'minimal',
      options: ['minimal', 'minimalism', 'abstract', 'geometric', 'gradient', 'dark',
        'nature', 'space', 'city', 'architecture', 'texture', 'vaporwave', 'topographic'],
      freeform: true, hint: 'search terms',
    },
    {
      key: 'source', label: 'wallpapers from', value: sourceId,
      options: null, sourceToken: true,
    },
    {
      key: 'format', label: 'as', value: prev.format ?? 'any',
      options: FORMATS, hint: 'kept files must really be this format',
    },
    {
      key: 'dir', label: 'into', value: prev.dir ?? defaultDir(),
      freeform: true, dirToken: true,
      hint: '↓ browse · type or paste a path',
    },
  ];

  for (const extra of src?.extra || []) {
    tokens.push({ ...extra, value: prev[extra.key] ?? extra.value, label: extra.label });
  }
  return tokens;
}

class SentenceEditor {
  constructor(sourceId, initial = {}) {
    this.tokens = buildTokens(sourceId, initial);
    this.index = 0;
    this.typing = null;
    this.menuOffset = 0;
    this.error = null;

    // browser / overlay / key-input state
    this.mode = 'menu';          // 'menu' | 'browse'
    this.overlay = false;
    this.keyInput = null;        // { env, value } while pasting an API key
    this.browse = null;          // { path, entries, index, offset }
    this.naming = null;          // new-folder name being typed
    this.recentDirs = [];
  }

  get token() { return this.tokens[this.index]; }
  get values() { return Object.fromEntries(this.tokens.map((t) => [t.key, t.value])); }

  // ── options / validation ───────────────────────────────────────────────

  options() {
    const t = this.token;
    if (t.sourceToken) return SOURCES.map((s) => s.id);
    if (t.dirToken && this.mode !== 'browse') return DIR_OPTIONS();
    let opts = t.options ? [...t.options] : [];
    if (this.typing) {
      const q = this.typing.toLowerCase();
      opts = opts.filter((o) => o.toLowerCase().includes(q));
      if (t.freeform !== false && !opts.includes(this.typing)) opts = [this.typing, ...opts];
    }
    return opts;
  }

  // ── core token ops (unchanged behaviour) ──────────────────────────────

  move(delta) {
    const n = this.tokens.length;
    this.index = (this.index + delta + n) % n;
    this._leaveModes();
    if (this.token.sourceToken) this._noteSource = true;
  }

  cycle(delta) {
    if (this.mode === 'browse') return this.browseMove(delta);
    const opts = this.options();
    if (!opts.length) return;
    const cur = opts.indexOf(this.typing ?? this.token.value);
    const next = cur === -1 ? (delta > 0 ? 0 : opts.length - 1)
      : (cur + delta + opts.length) % opts.length;
    this.menuOffset = Math.max(0, next - (MENU_H - 2));
    this._apply(opts[next]);
  }

  _apply(value) {
    const t = this.token;
    if (t.validate) {
      const err = t.validate(value);
      if (err) { this.error = err; return; }
    }
    t.value = value;
    this.error = null;
    if (t.sourceToken) {
      const keep = this.values;
      this.tokens = buildTokens(value, keep);
      this.index = this.tokens.findIndex((x) => x.key === 'source');
    }
  }

  typeChar(ch) {
    if (this.naming !== null) { this.naming += ch; return; }
    if (this.mode === 'browse') this._leaveModes(); // typing = paste-a-path mode
    this.typing = (this.typing ?? '') + ch;
    this.menuOffset = 0;
    this._apply(this.typing);
  }

  backspace() {
    if (this.naming !== null) { this.naming = this.naming.slice(0, -1); return; }
    if (this.mode === 'browse') return this.browseBack();
    if (this.typing === null) return;
    this.typing = this.typing.slice(0, -1);
    this.menuOffset = 0;
    if (this.token.freeform) this._apply(this.typing);
  }

  cancelTyping() { this.typing = null; this.naming = null; this.error = null; this.menuOffset = 0; }

  _leaveModes() { this.mode = 'menu'; this.browse = null; this.naming = null; this.overlay = false; this.keyInput = null; }

  // ── masked API-key input ──────────────────────────────────────────────
  startKeyInput(env) {
    this.keyInput = { env, value: '' };
    this.typing = null; this.mode = 'menu'; this.overlay = false; this.error = null;
  }
  keyChar(ch) { if (this.keyInput) this.keyInput.value += ch; }
  keyBackspace() { if (this.keyInput) this.keyInput.value = this.keyInput.value.slice(0, -1); }
  keyCancel() { this.keyInput = null; }

  commitError() {
    for (const t of this.tokens) {
      if (t.validate) {
        const err = t.validate(t.value);
        if (err) return `${t.key}: ${err}`;
      }
      if (t.sourceToken && !SOURCES.some((s) => s.id === t.value)) {
        const near = SOURCES.filter((s) => s.id.startsWith(String(t.value)[0]));
        return `unknown source "${t.value}"` +
          (near.length ? ` — did you mean ${near.map((s) => s.id).join(' / ')}?`
                       : ` — try ${SOURCES.map((s) => s.id).join(', ')}`);
      }
    }
    return null;
  }

  // ── folder browser ────────────────────────────────────────────────────

  async openBrowse(startAt) {
    let base = startAt ?? this.token.value;
    base = resolve(base.startsWith('~') ? join(homedir(), base.slice(1)) : base);
    if (!existsSync(base) || !this._isDir(base)) base = dirname(base);
    if (!existsSync(base) || !this._isDir(base)) base = downloadsDir();
    await this._loadBrowse(base);
    this.mode = 'browse';
    this.typing = null;
    this.error = null;
  }

  _isDir(p) { try { return statSync(p).isDirectory(); } catch { return false; } }

  async _loadBrowse(path) {
    let entries = [];
    try {
      const list = await readdir(path, { withFileTypes: true });
      entries = list
        .filter((e) => (e.isDirectory() || e.isSymbolicLink()) && !e.name.startsWith('.'))
        .map((e) => e.name)
        .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
    } catch (e) {
      this.error = `can't read ${path}: ${e.code || e.message}`;
    }
    this.browse = { path, entries, index: 0, offset: 0 };
    this.naming = null;
  }

  browseMove(delta) {
    const b = this.browse;
    if (!b || !b.entries.length) return;
    b.index = (b.index + delta + b.entries.length) % b.entries.length;
    b.offset = Math.min(Math.max(0, b.index - (MENU_H - 2)), Math.max(0, b.entries.length - MENU_H));
  }

  async browseEnter() { // space: descend into the highlighted folder
    const b = this.browse;
    if (!b?.entries.length) return;
    await this._loadBrowse(join(b.path, b.entries[b.index]));
  }

  async browseBack() { // ⌫: up one level
    const b = this.browse;
    if (!b) return;
    const parent = dirname(b.path);
    if (parent === b.path) return;
    const old = b.path.split(/[\\/]/).pop();
    await this._loadBrowse(parent);
    const i = this.browse.entries.indexOf(old);
    if (i >= 0) { this.browse.index = i; this.browse.offset = Math.max(0, i - (MENU_H - 2)); }
  }

  async browseNew() { // n then type a name, ⏎ creates it
    if (this.naming === null) { this.naming = ''; return; }
    const name = this.naming.trim();
    this.naming = null;
    if (!name) return;
    try {
      await mkdir(join(this.browse.path, name), { recursive: false });
      await this._loadBrowse(this.browse.path);
      const i = this.browse.entries.indexOf(name);
      if (i >= 0) this.browse.index = i;
    } catch (e) {
      this.error = e.code === 'EEXIST' ? `folder "${name}" already exists` : `${e.code || e.message}`;
    }
  }

  browseSelect() { // ⏎ in browse: take the current folder as the dir value
    if (!this.browse) return;
    this.token.value = this.browse.path;
    this.recentDirs = [this.browse.path, ...this.recentDirs.filter((d) => d !== this.browse.path)].slice(0, 5);
    this._leaveModes();
  }

  // ── overlay ───────────────────────────────────────────────────────────

  toggleOverlay(cfg) {
    this.overlay = !this.overlay;
    if (this.overlay) {
      const v = cfg?.values || {};
      const keys = cfg?.keys || {};
      this._overlayLines = [
        `${c.bold}saved preferences${c.reset}  ${c.dim}${configPath()}${c.reset}`,
        '',
        ...Object.entries(v).slice(0, 9).map(
          ([k, val]) => `  ${CYAN}${String(k).padEnd(10)}${c.reset} ${String(val)}`,
        ),
        '',
        `${c.bold}keys${c.reset} ${c.dim}(optional, stored locally)${c.reset}`,
        ...['UNSPLASH_ACCESS_KEY', 'PEXELS_API_KEY', 'PIXABAY_API_KEY'].map((k) =>
          `  ${k.padEnd(20)} ${keys[k] ? c.green + mask(keys[k]) + c.reset : c.dim + 'not set' + c.reset}`),
        '',
        `${c.dim}env vars always win · --reset clears · --no-save skips${c.reset}`,
      ];
    }
  }

  // ── rendering ─────────────────────────────────────────────────────────

  sentence() {
    let out = `${AMBER}${c.bold}download${c.reset} `;
    for (let i = 0; i < this.tokens.length; i++) {
      const t = this.tokens[i];
      if (i > 0 && t.label) out += `${c.dim}${t.label}${c.reset} `;
      const active = i === this.index;
      const val = String(t.value ?? '');
      out += active
        ? `${c.inverse}${CYAN}${c.bold} ${val || '…'} ${c.reset}`
        : `${CYAN}${val || c.dim + '…'}${c.reset}`;
      out += ' ';
    }
    return out;
  }

  _box(title, rows, foot) {
    const W = 60;
    const lines = [];
    lines.push(`  ${c.dim}┌ ${c.bold}${title}${c.reset}${c.dim} ${'─'.repeat(Math.max(2, W - sw(title)))}┐${c.reset}`);
    for (const r of rows) {
      lines.push(`  ${c.dim}│${c.reset}${padRow(r, W)}${c.dim}│${c.reset}`);
    }
    lines.push(`  ${c.dim}└${'─'.repeat(W)}┘${c.reset}`);
    if (foot) lines.push(foot);
    return lines;
  }

  _renderMenu() {
    const opts = this.options();
    const t = this.token;
    const title = this.typing !== null
      ? `type to filter — ⏎ to accept "${this.typing}"`
      : (t.hint || `choose a ${t.key}`);

    const rows = [];
    if (!opts.length) {
      rows.push(` ${c.italic}${c.dim}no match — keep typing, ⏎ uses your text${c.reset}`);
    } else {
      for (const o of opts.slice(this.menuOffset, this.menuOffset + MENU_H)) {
        const sel = o === (this.typing ?? t.value);
        rows.push(sel
          ? ` ${c.bold}${CYAN}› ${o}${c.reset}`
          : ` ${c.dim}  ${o}${c.reset}`);
      }
      if (opts.length > MENU_H) {
        rows.push(` ${c.dim}· · · ${opts.length} options${c.reset}`);
      }
    }
    return this._box(title, rows, null);
  }

  _renderBrowse() {
    const b = this.browse;
    const title = `in ${shortPath(b.path)}`;
    const rows = [];
    if (this.naming !== null) {
      rows.push(` ${AMBER}${c.bold}new folder: ${this.naming}▌${c.reset}  ${c.dim}⏎ create · esc cancel${c.reset}`);
    } else if (!b.entries.length) {
      rows.push(` ${c.italic}${c.dim}no folders here — n to create one, ⏎ to use this folder${c.reset}`);
    } else {
      for (const name of b.entries.slice(b.offset, b.offset + MENU_H)) {
        const sel = name === b.entries[b.index];
        rows.push(sel
          ? ` ${c.bold}${CYAN}› ${name}/${c.reset}`
          : ` ${c.dim}  ${name}/${c.reset}`);
      }
      if (b.entries.length > MENU_H) {
        rows.push(` ${c.dim}· · · ${b.entries.length} folders${c.reset}`);
      }
    }
    const foot = `  ${c.dim}space${c.reset} enter  ${c.dim}⌫${c.reset} up  ${c.dim}⏎${c.reset} select  ` +
      `${c.dim}n${c.reset} new  ${c.dim}type${c.reset} paste path  ${c.dim}esc${c.reset} close`;
    return this._box(title, rows, foot);
  }

  _renderOverlay() {
    return this._box('preferences · e or esc to close',
      this._overlayLines.map((l) => ' ' + l), null);
  }

  _renderKey() {
    const k = this.keyInput;
    const dots = '•'.repeat(Math.min(k.value.length, 28)) + (k.value.length > 28 ? '+' : '');
    return this._box(`paste ${k.env}`, [
      ` ${AMBER}${c.bold}${dots || '…'}${c.reset}${c.dim}  (${k.value.length} chars)${c.reset}`,
      ` ${c.dim}⏎ save locally · esc cancel · masked, never echoed${c.reset}`,
    ], null);
  }

  render() {
    const lines = [];
    lines.push('');
    lines.push('  ' + this.sentence());
    lines.push('');

    if (this.keyInput) lines.push(...this._renderKey());
    else if (this.overlay) lines.push(...this._renderOverlay());
    else if (this.mode === 'browse' && this.browse) lines.push(...this._renderBrowse());
    else lines.push(...this._renderMenu());

    lines.push('');
    if (this.error) {
      lines.push(`  ${c.bgRed}${c.bold}${c.white} ✖ ${this.error} ${c.reset}`);
    } else if (this.overlay) {
      lines.push(`  ${c.dim}e / esc${c.reset} close overlay`);
    } else {
      lines.push(
        `  ${c.dim}←→${c.reset} move   ${c.dim}↑↓${c.reset} value   ` +
        `${c.dim}type${c.reset} custom   ${c.dim}⏎${c.reset} grab   ${c.dim}e${c.reset} prefs   ` +
        `${c.dim}^K${c.reset} key   ${c.dim}esc${c.reset} quit`,
      );
    }
    return lines;
  }
}

function padRow(s, n) {
  const w = sw(s);
  return s + ' '.repeat(Math.max(1, n - w));
}

function shortPath(p) {
  const home = homedir();
  const s = p.startsWith(home) ? '~' + p.slice(home.length) : p;
  return s.length > 44 ? '…' + s.slice(-43) : s;
}


// ──────────────────────────────────────────────────────────────────
// src/cli.mjs
// ──────────────────────────────────────────────────────────────────
// wallgrab — bulk wallpaper downloader with an inline sentence editor.


const VERSION = '1.1.0';

// ─────────────────────────────────────────────────────────────── arg parsing

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help' || a === '-h') out.help = true;
    else if (a === '--version' || a === '-v') out.version = true;
    else if (a === '--yes' || a === '-y') out.yes = true;
    else if (a === '--sources') out.sources = true;
    else if (a === '--reset') out.reset = true;
    else if (a === '--no-save') out.noSave = true;
    else if (a === '--prefs') out.prefs = true;
    else if (a === '--keys') out.keys = true;
    else if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next !== undefined && !next.startsWith('--')) { out[key] = next; i++; }
      else out[key] = true;
    } else out._.push(a);
  }
  return out;
}

function help() {
  const themes = Object.keys(THEME).join(' · ');
  return `${banner('ocean')}
${rule('─', 74, 'ocean')}

  ${c.bold}Usage${c.reset}
    wallgrab                          interactive sentence editor
    wallgrab ${c.dim}[flags]${c.reset} --yes           non-interactive, for scripts & CI

  ${c.bold}Flags${c.reset}
    ${CYAN}--source${c.reset} <id>        ${c.dim}wallhaven · unsplash · nasa · openverse · pexels${c.reset}
                         ${c.dim}pixabay · artic · met · picsum · github · reddit${c.reset}
    ${CYAN}--query${c.reset} <text>       search terms              ${c.dim}(default: minimal)${c.reset}
    ${CYAN}--count${c.reset} <n>          how many to fetch         ${c.dim}(default: 100)${c.reset}
    ${CYAN}--dir${c.reset} <path>         output folder   ${c.dim}(default: ~/Downloads/wallgrab)${c.reset}
    ${CYAN}--format${c.reset} <ext>       jpg png webp gif avif any ${c.dim}(default: any)${c.reset}
    ${CYAN}--jobs${c.reset} <n>           parallel downloads        ${c.dim}(default: 6)${c.reset}
    ${CYAN}--theme${c.reset} <name>       ${themes}
    ${CYAN}--yes${c.reset}, -y            skip the editor, run immediately
    ${CYAN}--keys${c.reset}              interactive API-key setup (masked, stored locally)
    ${CYAN}--prefs${c.reset}             print stored preferences + keys (masked)
    ${CYAN}--reset${c.reset}             wipe stored preferences and exit
    ${CYAN}--no-save${c.reset}           don't remember this run's preferences
    ${CYAN}--sources${c.reset}            list every source and exit
    ${CYAN}--version${c.reset}, -v        print version
    ${CYAN}--help${c.reset}, -h           this screen

  ${c.bold}In the editor${c.reset}
    ${CYAN}← →${c.reset}  move between the highlighted words
    ${CYAN}↑ ↓${c.reset}  cycle that word's values
    ${CYAN}type${c.reset} filter the list, or paste your own value
    ${CYAN}⏎${c.reset}    run it        ${CYAN}e${c.reset} preferences overlay   ${CYAN}esc${c.reset} quit
    ${CYAN}ctrl+k${c.reset} paste an API key for the current source (masked)

  ${c.bold}Folder browser${c.reset} ${c.dim}(select the ${CYAN}into${c.reset}${c.dim} token, press ↓)${c.reset}
    ${CYAN}space${c.reset} enter folder   ${CYAN}⌫${c.reset} parent   ${CYAN}⏎${c.reset} select current
    ${CYAN}n${c.reset}     new folder     ${CYAN}type${c.reset} paste a full path   ${CYAN}esc${c.reset} close

  ${c.bold}Preferences${c.reset}
    Your last count · query · source · folder · options and any API keys are
    remembered in ${c.dim}${configPath()}${c.reset}
    and restored on the next run. Env vars always win over stored keys.

  ${c.bold}API keys${c.reset} ${c.dim}(only unsplash, pexels and pixabay need one)${c.reset}
    ${AMBER}export${c.reset} UNSPLASH_ACCESS_KEY=xxx    ${c.dim}https://unsplash.com/developers${c.reset}
    ${AMBER}export${c.reset} PEXELS_API_KEY=xxx         ${c.dim}https://www.pexels.com/api/${c.reset}
    ${AMBER}export${c.reset} PIXABAY_API_KEY=xxx        ${c.dim}https://pixabay.com/api/docs/${c.reset}
`;
}

function listSources() {
  const rows = SOURCES.map((s) => {
    const key = s.keyEnv ? `${c.yellow}needs ${s.keyEnv}${c.reset}` : `${c.green}no key${c.reset}`;
    return `  ${CYAN}${padStr(s.id, 11)}${c.reset} ${padStr(s.name, 24)} ${key}  ${c.dim}${s.blurb}${c.reset}`;
  });
  return `${banner('grape')}\n${rows.join('\n')}\n`;
}

const padStr = (s, n) => s + ' '.repeat(Math.max(0, n - s.length));

const KEY_ENVS = ['UNSPLASH_ACCESS_KEY', 'PEXELS_API_KEY', 'PIXABAY_API_KEY'];

// Read a line without echoing it (shows • per char). null = cancelled.
function readSecret(label) {
  if (!process.stdin.isTTY) {
    console.log(`  ${c.dim}${label}: not a TTY — set the env var instead${c.reset}`);
    return Promise.resolve(null);
  }
  return new Promise((res) => {
    process.stdout.write(`  ${label} ${c.dim}(hidden)${c.reset}: `);
    let val = '';
    process.stdin.setRawMode(true);
    process.stdin.resume();
    const done = (v) => {
      process.stdin.removeListener('data', on);
      process.stdin.setRawMode(false);
      process.stdin.pause();
      process.stdout.write('\n');
      res(v);
    };
    const on = (b) => {
      for (const ch of b.toString()) {
        if (ch === '\r' || ch === '\n') return done(val);
        if (ch === '\x03' || ch === '\x1b') return done(null);
        if (ch === '\x7f' || ch === '\b') {
          if (val) { val = val.slice(0, -1); process.stdout.write('\b \b'); }
          continue;
        }
        if (ch >= ' ') { val += ch; process.stdout.write('•'); }
      }
    };
    process.stdin.on('data', on);
  });
}

async function keysWizard(cfg, theme) {
  process.stdout.write(banner(theme) + '\n' + rule('─', 74, theme) + '\n\n');
  console.log(`  ${c.bold}API key setup${c.reset} — stored locally at ${c.dim}${configPath()}${c.reset}`);
  console.log(`  ${c.dim}env vars always win · enter = keep · esc = skip${c.reset}\n`);
  cfg.keys = cfg.keys || {};

  for (const env of KEY_ENVS) {
    const src = SOURCES.find((s) => s.keyEnv === env);
    const cur = process.env[env] ? `${c.green}(env)${c.reset}`
      : cfg.keys[env] ? `${c.green}(stored ${mask(cfg.keys[env])})${c.reset}` : `${c.dim}(not set)${c.reset}`;
    console.log(`  ${CYAN}${env}${c.reset}  ${c.dim}${src?.name || ''}${c.reset}  ${cur}`);
    console.log(`    ${c.dim}${src?.keyHint || ''}${c.reset}`);
    const v = await readSecret('   paste new key');
    if (v === null) { console.log(`    ${c.dim}skipped${c.reset}\n`); continue; }
    if (v === '') { console.log(`    ${c.dim}kept${c.reset}\n`); continue; }
    cfg.keys[env] = v.trim();
    console.log(`    ${c.green}✓ saved${c.reset}\n`);
  }

  await saveConfig({ values: cfg.values || {}, keys: cfg.keys, recentDirs: cfg.recentDirs || [], theme }).catch(() => {});
  console.log(`  ${c.green}✓${c.reset} done — now run ${CYAN}wallgrab${c.reset} and pick ${SOURCES.filter((s) => s.keyEnv).map((s) => s.id).join(' / ')}\n`);
  return 0;
}

// ─────────────────────────────────────────────────────────────── editor loop

async function runEditor(theme, cfg, persist) {
  const editor = new SentenceEditor(cfg?.values?.source || 'wallhaven', cfg?.values || {});
  editor.recentDirs = cfg?.recentDirs || [];
  process.stdout.write(hideCursor);

  // Redraw clears *downward* from the region start, so the banner printed
  // above is never touched (this is what the old upward-clearing draw broke).
  let printed = 0;
  const draw = () => {
    const next = editor.render();
    if (printed) {
      process.stdout.write(cursorUp(printed));
      for (let i = 0; i < printed; i++) process.stdout.write(clearLine + '\n');
      process.stdout.write(cursorUp(printed));
    }
    process.stdout.write(next.join('\n') + '\n');
    printed = next.length;
  };

  draw();
  let busy = false;

  return new Promise((resolve) => {
    // await persist before resolving, or process.exit() in main will kill the
    // async config write before it lands
    const finish = async (values) => {
      cleanup();
      if (!values) await persist(editor.values, editor.recentDirs); // remember even on quit
      resolve(values);
    };

    const handle = async (s) => {
      const t = editor.token;

      // masked key input captures everything while active
      if (editor.keyInput) {
        if (s === '\r' || s === '\n') {
          const { env, value } = editor.keyInput;
          editor.keyCancel();
          const v = value.trim();
          if (v) {
            cfg.keys = { ...cfg.keys, [env]: v };
            await saveConfig({ values: editor.values, keys: cfg.keys, recentDirs: editor.recentDirs, theme }).catch(() => {});
          }
          return;
        }
        if (s === '\x1b') { editor.keyCancel(); return; }
        if (s === '\x7f' || s === '\b') { editor.keyBackspace(); return; }
        if (s === '\x15') { editor.keyInput.value = ''; return; }
        for (const ch of s) if (ch >= ' ' && ch.charCodeAt(0) < 127) editor.keyChar(ch);
        return;
      }

      if (s === '\x0b') {                                                    // ctrl+k → key for current source
        const src = byId(editor.values.source);
        if (src?.keyEnv) editor.startKeyInput(src.keyEnv);
        else editor.error = 'current source needs no key — try unsplash / pexels / pixabay, or `wallgrab --keys`';
        return;
      }

      if (s === '\x03') return finish(null);                                   // ctrl+c
      if (s === '\x1b' && s.length === 1) {                                    // esc
        if (editor.overlay) { editor.toggleOverlay(cfg); return; }
        if (editor.naming !== null) { editor.naming = null; return; }
        if (editor.mode === 'browse') { editor._leaveModes(); return; }
        return finish(null);
      }
      if (s === '\x1b[D') { editor.move(-1); return; }
      if (s === '\x1b[C' || s === '\t') { editor.move(1); return; }

      if (s === '\x1b[A') { editor.cycle(-1); return; }
      if (s === '\x1b[B') {
        if (editor.overlay) return;
        if (t.dirToken && editor.mode !== 'browse') { await editor.openBrowse(); return; }
        editor.cycle(1);
        return;
      }

      if (s === '\r' || s === '\n') {
        if (editor.overlay) { editor.toggleOverlay(cfg); return; }
        if (editor.naming !== null) { await editor.browseNew(); return; }
        if (editor.mode === 'browse') { editor.browseSelect(); return; }
        editor.cancelTyping();
        const err = editor.commitError();
        if (err) { editor.error = err; return; }
        editor.recentDirs = [editor.values.dir, ...editor.recentDirs.filter((d) => d !== editor.values.dir)].slice(0, 5);
        return finish(editor.values);
      }

      if (s === '\x7f' || s === '\b') { editor.backspace(); return; }
      if (s === '\x15') { editor.cancelTyping(); return; }                      // ctrl+u
      if (s === ' ') {
        if (editor.mode === 'browse' && editor.naming === null) { await editor.browseEnter(); return; }
        editor.typeChar(' ');
        return;
      }
      if (s === 'n' && editor.mode === 'browse' && editor.naming === null) { editor.naming = ''; return; }
      if (s === 'e' && editor.mode !== 'browse' && editor.typing === null && !editor.overlay) {
        editor.toggleOverlay(cfg);
        return;
      }

      for (const ch of s) {
        if (ch >= ' ' && ch.charCodeAt(0) < 127) editor.typeChar(ch);
      }
    };

    const onData = (buf) => {
      if (busy) return;
      busy = true;
      handle(buf.toString())
        .then(() => draw())
        .finally(() => { busy = false; });
    };

    const cleanup = () => {
      process.stdin.removeListener('data', onData);
      if (process.stdin.isTTY) process.stdin.setRawMode(false);
      process.stdin.pause();
      process.stdout.write(showCursor);
    };

    if (process.stdin.isTTY) process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.on('data', onData);
  });
}

// ────────────────────────────────────────────────────────────────── running

async function resolveKey(src, cfg, wantSave) {
  if (!src.keyEnv) return { ok: true };
  const envKey = process.env[src.keyEnv];
  const stored = cfg?.keys?.[src.keyEnv];
  const key = envKey || stored;
  if (key) {
    // persist an env-provided key so the next run needs nothing
    if (envKey && wantSave && stored !== envKey) {
      cfg.keys = { ...cfg.keys, [src.keyEnv]: envKey };
    }
    return { ok: true, key, from: envKey ? 'env' : 'stored' };
  }
  return {
    ok: false,
    msg: `${src.name} needs a free API key.\n` +
         `    ${CYAN}wallgrab --keys${c.reset}          set it interactively (masked, stored locally)\n` +
         `    ${CYAN}ctrl+k${c.reset} in the editor     set it for the current source\n` +
         `    ${AMBER}export ${src.keyEnv}=your_key${c.reset}   ${c.dim}(it will be remembered)${c.reset}\n` +
         `    ${c.dim}${src.keyHint}${c.reset}\n\n` +
         `    Or pick a no-key source: ${SOURCES.filter((s) => !s.keyEnv).map((s) => s.id).join(', ')}`,
  };
}

async function execute(values, jobs, ctx) {
  const { theme, cfg, wantSave } = ctx;
  const src = byId(values.source);
  if (!src) { console.log(`${c.red}unknown source: ${values.source}${c.reset}`); return 1; }

  const keyRes = await resolveKey(src, cfg, wantSave);
  if (!keyRes.ok) { console.log('\n' + keyRes.msg + '\n'); return 1; }

  const params = { query: values.query, count: Math.max(1, parseInt(values.count, 10) || 100), ...values };

  console.log(`\n  ${CYAN}⟡${c.reset} searching ${c.bold}${src.name}${c.reset} for ${c.bold}"${params.query}"${c.reset} ${c.dim}(wanting ${params.count})${c.reset}` +
    (keyRes.from ? `  ${c.dim}key: ${keyRes.from}${c.reset}` : ''));

  let items;
  try {
    items = await src.search(params, keyRes.key);
  } catch (e) {
    console.log(`  ${c.bgRed}${c.bold}${c.white} ✖ ${c.reset} ${e.message}\n`);
    if (/HTML instead of JSON|403|429|503/.test(e.message)) {
      console.log(`  ${c.dim}That usually means the source rate-limited this IP. Wait a few`);
      console.log(`  minutes, lower --count, or try another source.${c.reset}\n`);
    }
    return 1;
  }

  if (!items?.length) { console.log(`  ${c.yellow}no results for that query — try different terms${c.reset}\n`); return 1; }
  console.log(`  ${c.green}✓${c.reset} found ${c.bold}${items.length}${c.reset} images\n`);

  let tick = 0;
  const onProgress = (st) => {
    const pct = st.total ? st.done / st.total : 0;
    const rate = st.bytes / Math.max(0.001, (Date.now() - st.startedAt) / 1000);
    const eta = st.done > 0 ? (st.bytes / st.done) * (st.total - st.done) / rate : 0;
    const spin = SPINNER[tick++ % SPINNER.length];
    process.stdout.write(
      '\r' + clearLine +
      `  ${CYAN}${spin}${c.reset} ${bar(pct, 26)} ` +
      `${c.bold}${String(st.done).padStart(4)}/${st.total}${c.reset} ` +
      `${c.green}${st.ok}✓${c.reset} ${c.dim}${st.skipped}–${c.reset} ${c.red}${st.failed}✖${c.reset} ` +
      `${AMBER}${humanBytes(st.bytes)}${c.reset} ${c.dim}@ ${humanBytes(rate)}/s · eta ${humanTime(eta)}${c.reset}`,
    );
  };

  const st = await downloadAll(items, {
    dir: values.dir, format: values.format || 'any', concurrency: jobs, onProgress,
  });
  process.stdout.write('\n\n');

  const lines = [
    `${c.green}${c.bold}${st.ok}${c.reset} wallpapers saved  ${c.dim}(${humanBytes(st.bytes)})${c.reset}`,
    st.skipped ? `${c.yellow}${st.skipped}${c.reset} skipped  ${c.dim}(already there, or wrong format)${c.reset}` : null,
    st.failed ? `${c.red}${st.failed}${c.reset} failed` : null,
    `${c.dim}${st.elapsed.toFixed(1)}s · ${values.dir}${c.reset}`,
  ].filter(Boolean);
  console.log(box(lines, 'done', 'mint'));

  if (st.errors.length) {
    console.log(`\n  ${c.dim}first few problems:${c.reset}`);
    for (const e of st.errors.slice(0, 5)) console.log(`    ${c.dim}·${c.reset} ${e.name} ${c.dim}— ${e.why}${c.reset}`);
  }
  console.log(`\n  ${gradient('grab more →', ['#11998e', '#38ef7d'])} ${c.dim}run wallgrab again — your preferences are saved${c.reset}\n`);
  return 0;
}

// ────────────────────────────────────────────────────────────────────── main

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const cfg = (await loadConfig()) || { values: {}, keys: {}, recentDirs: [] };
  const theme = args.theme && THEME[args.theme] ? args.theme
    : (cfg.theme && THEME[cfg.theme] ? cfg.theme : 'sunset');
  const wantSave = !args.noSave;

  if (args.reset) {
    const did = await clearConfig();
    console.log(did ? `  ${c.green}✓${c.reset} cleared ${configPath()}\n` : `  ${c.dim}nothing to clear${c.reset}\n`);
    return 0;
  }
  if (args.help) { console.log(help()); return 0; }
  if (args.version) { console.log(`wallgrab ${VERSION}`); return 0; }
  if (args.sources) { console.log(listSources()); return 0; }
  if (args.keys) { return keysWizard(cfg, theme); }
  if (args.prefs) {
    console.log(`  ${c.bold}stored at${c.reset} ${configPath()}\n`);
    console.log(`  ${c.bold}values${c.reset}`);
    for (const [k, v] of Object.entries(cfg.values || {})) console.log(`    ${CYAN}${padStr(k, 10)}${c.reset} ${v}`);
    console.log(`  ${c.bold}keys${c.reset}`);
    for (const k of ['UNSPLASH_ACCESS_KEY', 'PEXELS_API_KEY', 'PIXABAY_API_KEY']) {
      console.log(`    ${padStr(k, 20)} ${cfg.keys?.[k] ? c.green + mask(cfg.keys[k]) + c.reset : c.dim + 'not set' + c.reset}`);
    }
    console.log('');
    return 0;
  }

  const persist = async (values, recentDirs) => {
    if (!wantSave) return;
    await saveConfig({
      values,
      keys: cfg.keys || {},
      recentDirs: recentDirs || [],
      theme,
    }).catch(() => {});
  };

  const jobs = parseInt(args.jobs, 10) || 6;
  const ctx = { theme, cfg, wantSave };

  // non-interactive: explicit --source runs straight away
  if (args.yes || args.source) {
    const src = byId(args.source || 'wallhaven');
    if (!src) { console.log(`${c.red}unknown source "${args.source}"${c.reset}\nTry: ${SOURCES.map((s) => s.id).join(', ')}`); return 1; }
    const prev = cfg.values || {};
    const values = {
      source: src.id,
      count: String(args.count ?? prev.count ?? src.defaults.count),
      query: args.query ?? prev.query ?? src.defaults.query,
      format: args.format ?? prev.format ?? 'any',
      dir: args.dir ?? prev.dir ?? defaultDir(),
    };
    for (const extra of src.extra) {
      values[extra.key] = args[extra.key] ?? prev[extra.key] ?? extra.value;
    }
    const code = await execute(values, jobs, ctx);
    if (code === 0 && wantSave) await persist(values, cfg.recentDirs);
    return code;
  }

  process.stdout.write(banner(theme));
  process.stdout.write('\n' + rule('─', 74, theme) + '\n');

  const values = await runEditor(theme, cfg, persist);
  if (!values) { console.log(`\n  ${c.dim}preferences saved — see you next time${c.reset}\n`); return 0; }

  const code = await execute(values, jobs, ctx);
  if (code === 0 && wantSave) await persist(values, values ? [values.dir, ...(cfg.recentDirs || []).filter((d) => d !== values.dir)].slice(0, 5) : cfg.recentDirs);
  return code;
}

const code = await main().catch((e) => {
  console.error(`\n${c.bgRed}${c.bold}${c.white} ✖ ${c.reset} ${e.stack || e.message}\n`);
  return 1;
});
process.stdout.write(showCursor);
process.exit(code);

